src/Component/Navbar.js, src/style/Navbar.css
=> added title on the sidebar

src/Component/Home.js, src/Component/Navbar.js, src/style/Navbar.css
Fixed #12
With the use of localstorage I have created a logic for sidebar by filtering the content according to category.
Let me know for any update in code
=> Fixed Sidebar Fitler 

src/index.css
Generally we have white and grey colored scroll bar provided by the bowser but it doesn't matches with our default color of the website and same problem was with your's website too. So I wrote a code to modify the scroll bar and now it looks as follows:
=> Modified Default Scroll Bar

src/Component/Navbar.js, src/style/Navbar.css
Added hover effects for sidebar contents so it will scale and text will get underlined on hover. #24 
#Hacktoberfest
=> Added hover effects for sidebar contents

src/Component/Navbar.js
Fixed issue #33 
#Hacktoberfest
=> Fixed bug in sidebar home button

src/Component/About.js, src/style/About.css
This pr is to resolve issue #15
=> Add contributor page to the website issue #15

src/Component/Home.js, src/style/Pagination.css
Fixes- #43 
Video displaying changes on website:- 
https://github.com/HimanshuNarware/Devlabs/assets/116253210/d8eed38c-6030-469f-a8fe-e26f4b961eba
Kindly merge,
Thank you for your consideration
=> page-index displayed at each page dynamically

src/Component/Home.js, src/Slice/DataSlice.js
Fixes #52 
Also fixes the repetition of bookmarks in Bookmarks section
=> Added localstorage functionality to the bookmark section

src/Component/Navbar.js
Fix the issue with sidebar menu icon not changing to close (#53)
=> Fix the issue with sidebar menu icon not changing to close (#53)

src/DB/product.json
hello, i would like to add planet scale to list product
please kindly to reviewing my pull request
thank you
=> add planet scale to db/product.json

src/App.js, src/Component/NotFound.js, src/style/NotFound.css
Fixes: Issue: Website does't have a 404 page #58
=> Fixes: Issue: Website does't have a 404 page #58

src/Component/BookMark.js, src/Slice/DataSlice.js
this is the issue number Issue: "Need to Add Bookmark Deletion Feature" #69
=> Fixes: Issue: "Need to Add Bookmark Deletion Feature" #69

src/style/Home.css, src/style/Navbar.css
Enhancing User Experience with Hover Effects on Cards #71
Here is the video
https://github.com/HimanshuNarware/Devlabs/assets/130299888/7fbcbd72-da76-4e35-a427-f5a830b5b0c6
=> Fixes: Enhancing User Experience with Hover Effects on Cards #71

src/style/BookMark.css
fix issue #78 
Responsiveness of tabs on the home page
=> Responsiveness of tabs on the home page

src/Component/Navbar/NavbarRight.js, src/style/Navbar.css
Fixes- #86 
Any suggestions/fixes are highly appreciated.
Video link:-
https://github.com/HimanshuNarware/Devlabs/assets/116253210/d6cd2fc5-c5c2-4ce6-a1dc-7025ce7b187c
=> Search ui updated

src/Component/Home.js, src/style/BookMark.css, src/style/Home.css
Updated the card UI design.
Please let me know if there are any changes to be made.
Thank you!
=> updated the card design

src/Component/Home.js, src/style/Home.css
Homepage should look good now
Fix #99
=> Homepage responsiveness

src/App.css, src/Component/Home.js, src/Component/Navbar/Navbar.js, src/Component/Navbar/NavbarRight.js
hey there i have implemented search functionality against the issue #101  and it is working fine absolutely. now you can merge it your main repo. If any more kind of help needed i will be happy to contribute in your project more.
=> working search function

src/style/Navbar.css
@HimanshuNarware  In this pr I have resolved the overflow issue #35 .
https://github.com/HimanshuNarware/Devlabs/assets/97834009/70b6d7fa-2566-40b3-8aca-66b84c41e047
=> resolve overflow issue with sidebar issue #35

src/Component/Sidebar/Sidebar.js, src/style/Navbar.css
Fixed sidebar scrolling and added scrollbar. The sidebar was not scrolling down properly.
=> Fixed sidebar scroll

src/Component/About.js, src/style/About.css
made necessary changes to Improve the UI of the about section
=> Improve the UI of the about section

package-lock.json, package.json, public/index.html, src/Component/Navbar/Navbar.js, src/index.css, src/index.js, src/style/BookMark.css, src/style/Footer.css, src/style/Home.css, src/style/Navbar.css
Addressing issue #90 , I've employed  Darkmode.js library to implement both light and dark user interfaces.
=> Added lightmode and darkmode feature

package-lock.json, src/DB/product.json
**Fixes : #125** 
- before : 
- After :
=> Updated Sass logo link 

package-lock.json, src/index.css, src/style/Navbar.css
Hi @HimanshuNarware , fixed #122
=> Fixed sidebar scroll and added scrollbar

src/DB/product.json, src/style/Navbar.css
#133 when we hover on navbar elements like home, about us , bookmark and opensource we would have a better animation.
=> #133 Animation On Hovering On Navbar elements

src/index.css, src/style/Navbar.css
Hi @HimanshuNarware, here is the fixed scrollbar Pull Request. Sorry that i forgot to push my code earlier, so here is the updated branch with the necessary changes.
=> changed scrollbar background

.gitignore, package-lock.json, src/App.js, src/Component/Footer.js, src/Component/Home.js, src/Component/Review.js, src/style/Footer.css, src/style/Review.css
issue resolved: #143
A page for users to send their thoughts to the website owner.
Added Link to the review page in the footer
=> Review page created

src/style/About.css
@HimanshuNarware , this pr is for issue #148 . Kindly review and merge.
=> Change profile button style in about page to match with background

src/DB/product.json
This PR made a correction to an incorrect link in the apps.
- This is the submission to issue #153 
-  And the submission to issue #154
=> bug: dashboard ui kit is not loading

README.md, backend/package-lock.json, backend/package.json, backend/src/app.js, backend/src/config/nodemailer.js, backend/src/controllers/specialController.js, backend/src/routes/special.js, frontend/src/Component/Review.js
issue resolved #163 
Using nodemailer, created `transporter` instance. Also created a `mailOptions` dictionary defining "to" and "from" for the mail.
Generates email body using simple html layout and using the predefined `transporter` instance to send the mail. Note that the user sending the mail does not get any mail. User is alerted when the mail is sent.
defining router for mailing endpoint.
Modified code to send post request to the endpoint.
add following environment variables to the `backend` environment file
```bash
MAIL=<mail from which send to yourself>
PASSWORD=<passkey corresponding to above mail>
```
https://github.com/HimanshuNarware/Devlabs/assets/96971096/529b2d36-4c51-40f4-b4f6-6e39b58ad574
=> mailing endpoint and mailing feature

frontend/src/Component/Home.js, frontend/src/Component/OpenSource.js
> On receiving data from the backend, "backend data loaded" is logged to console.
> "json data loaded" logged to console otherwise.
=> default data setup

frontend/package-lock.json, frontend/package.json, frontend/src/Component/BackToTopButton.js
This PR fixes issue no. #174 .
Updated existing dependency.
Fixed the issue/error.
To get more info about this PR, Kindly check the issue no. #174
=> fixing Inital-local-setup-error-due-to-static-image-file-location

frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarLeft.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/Component/Sidebar/SidebarContent.js, frontend/src/style/Navbar.css
Fixes: #179 
Added animation in the navmenu and in the sidebar.
Mapped the sidebar contents using an array instead of rendering them individually.
=> Added animation in navbar and sidebar

frontend/src/Component/Home.js, frontend/src/style/Home.css
Improved Changes:
1) When user clicks Add Bookmark button then a popup showing "Bookmark Added" comes
Solved Issue #185 
Video:
https://github.com/HimanshuNarware/Devlabs/assets/94885893/24a0a222-884c-4405-b370-568b7620bb81
=> Create Bookmark Notification

frontend/src/index.css, frontend/src/style/Navbar.css
=> Fixed The Pagination issue

frontend/src/App.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/NavbarRight.js
=> Updated Search and Pagination

frontend/src/App.js, frontend/src/Component/Navbar/NavbarRight.js
=> clear searchQuery after 1s

frontend/src/Component/Footer.js
=> fix typeof  mistake in code .

frontend/src/Component/Sidebar/Sidebar.js, frontend/src/style/Navbar.css
@HimanshuNarware 
-Corrected error
-Added Smooth transition of sidebar elements
-Added margin at bottom of sidebar to access last section .
=> #35 Over flow issue resolved 

frontend/src/DB/product.json
Done #212 
I added a new tool called **PortSwigger** in the "ethical" category
=>  Added New tool

frontend/src/index.css, frontend/src/style/Footer.css, frontend/src/style/Navbar.css
Fixed the issue of images not shown properly in dark mode as mentioned in https://github.com/HimanshuNarware/Devlabs/issues/198
=> Fixed images in Dark Mode

frontend/src/Component/NotFound.js, frontend/src/style/NotFound.css
As mentioned in issue https://github.com/HimanshuNarware/Devlabs/issues/193
=> Fixed the Go Home button on Error Page

frontend/src/style/Home.css
**Card Layout**
Here is the final result as discussed we have the unstandard layout as previous
https://github.com/HimanshuNarware/Devlabs/assets/109230049/acfc097b-018c-45ed-8ccd-a9b107f30cd4
=> Card-layout-fixed

backend/init/sampleToolsData.js, backend/package-lock.json, backend/package.json, backend/src/app.js, backend/src/config/ExpressError.js, backend/src/controllers/userController.js, backend/src/models/Tool.js, backend/src/models/User.js, backend/src/routes/user.js
#222 , Issue solved from my side! Please check and let me know if any changes required.
developed complete functionality of **signup and login** + developed **bookmarks** linking functionality with user account (backend)
https://github.com/HimanshuNarware/Devlabs/assets/142862928/a66897ce-925b-46a3-bb64-0e61ad06c96f
https://github.com/HimanshuNarware/Devlabs/assets/142862928/b82216bd-5498-4b8b-b03d-03c423da6cbe
Check the next comment as well! 😄 
(If you like my work, please assign me #241 to link all this functionality in the frontend side of website and make it actually user-ready)
=> Signup/Login + Bookmarks (linking with user account)

frontend/src/Component/Footer.js, frontend/src/Component/Home.js, frontend/src/Component/OpenSource.js, frontend/src/index.css, frontend/src/style/BookMark.css, frontend/src/style/Home.css, frontend/src/style/Navbar.css, frontend/src/style/Pagination.css
I have completed the UI Fixes as suggested in the Issue [215](https://github.com/HimanshuNarware/Devlabs/issues/215).
Also formatted the code for some files better readability.
=> UI Fixes (Footer + Responsive)

frontend/src/Component/Navbar/NavbarRight.js
#245 Revert Back to Home screen After Search Anything .
Use Case  :- When user search anything like scaler and then when user want to go back then Directly press enter after click on search bar
https://github.com/HimanshuNarware/Devlabs/assets/118350936/593d530d-b4fa-4408-9e6e-a0539a80e9f9
=> After Searching the user can go back by pressing Enter

frontend/src/style/About.css, package-lock.json
Now logo and description of logo is visible in single screen without scrolling. 
issue no is #283
=> About section is fixed

frontend/src/DB/product.json
=> updated products icon

frontend/src/style/About.css, frontend/src/style/Home.css
=> Added shadows to the buttons in home and about sections.

frontend/src/Component/Home.js
Issue #220 
There was no message in case the search result was empty.
Show a message in case search result is empty.
https://github.com/HimanshuNarware/Devlabs/assets/46455250/10e9d03a-2ea3-4201-853d-d6d4e068e623
=> fix: show message when searched result is empty

frontend/src/Component/Navbar/NavbarLeft.js, frontend/src/style/Navbar.css
**Description:**
This PR enhances the functionality of the navbar by adding the ability to close it when the user clicks on any item inside it. Previously, the navbar could only be toggled open or closed by clicking on the navbar toggle button. With this update, a click outside the navbar or on any navbar item will now close the navbar.
Changes:
1. Added an event listener to the document body to handle clicks outside the navbar, triggering the navbar to close.
2. Modified the NavbarLeft component to include an onClick handler for each item inside the navbar, which closes the navbar when clicked.
3. Added appropriate comments to highlight the changes made for clarity and maintainability.
4. I have added a transition effect that will be triggered when the navbar is closed.
These changes …
=> Enhance navbar functionality: Close navbar on item click

backend/src/models/Tool.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/DB/product.json
- Added the new category called "productivity" and also add some tools as well #289
=> Add new category

README.md
1. [Update README.md .. worked on about section]
2. [Update README.md worked on mission section]
3. [Update README.md updated Tech stack]
4. [Update README.md corrected typo]
5. [Update README.md quick start section]
6. [Update README.md worked on installation section]
7. [Update README.md .. worked on about section]
=> Updated Readme document  #260 resolved

frontend/src/Component/BookMark.js, frontend/src/style/BookMark.css
This PR introduces pagination for bookmarks and responsive design changes to improve the user experience on different screen sizes.
1. Added pagination for bookmarks to improve loading times and user experience.
2. Implemented responsive design changes for the bookmark container using CSS media queries.
3. Adjusted the grid-template columns for different screen sizes to ensure optimal display of bookmarks.
4. Issue No: #265
https://github.com/HimanshuNarware/Devlabs/assets/140513098/9f2e9333-84c4-491a-a844-d5b8cbc44451
=> Add Pagination for bookmarks and responsive design changes

frontend/src/Component/Navbar/NavbarRight.js
resolved the issue #230 
Added on key press seach with debounce of 300ms time span
=> Search on key press #230

frontend/src/Component/Sidebar/Sidebar.js
bug is fixed,
i have gone through bug and fixed the bug  with out interrupting remaining code 
Thank you
=> bug-fix issue #308

frontend/public/index.html
Fixed Issue #274 
Added some important meta tags that enhance the SEO of the website.
Testing using Google Lighthouse.
=> Added meta tags to increase SEO performance

backend/src/config/database.js, backend/src/controllers/specialController.js, backend/src/models/reviewForm.js, frontend/package-lock.json, frontend/package.json
I have solved the issue #267,  In this now the review form data is store in the backend and the owner get mailed also.
**submitting the form**
**storing the data in the backend**
**also getting the mail**
Hope, you like my work.
=> review-form store in backend

frontend/src/DB/product.json
Hello PA
Fixed issue number - #252 
Added Screenshot:-
=> added coursera website successfully  #252 

frontend/src/Component/Rate.js, frontend/src/Component/Review.js
issue no: #317 
i have added a rating system in the feedback section .
Used a separate component to create a rate system and used it in the Review.js part
=> Rating System in Feedback Section #317

frontend/src/style/Home.css
This makes the UI look more cleaner and smooth. Also the button hover color i changed it to match the color theme.
=> Issue:331 - Added smooth hovering effects for cards.

frontend/src/style/Navbar.css
#332 search bar is not visible in the  mobile view .
Before :- In mobile view the user didn't see the search bar .
After :- User can see search bar in the middle of the navbar .
=> Fixed search bar is not visible in the  mobile view

.idea/.gitignore, .idea/Devlabs.iml, .idea/modules.xml, .idea/vcs.xml, frontend/package-lock.json, frontend/src/Component/Home.js, frontend/src/style/About.css, frontend/src/style/Footer.css
This PR will add the feature of the home screen updation on typing something in the search bar if it matches with the available product name's spelling.
fixes #337 
Uploading Recording 2024-05-18 135258.mp4…
=> Feature added : Home screen update on typing in the search bar

frontend/package-lock.json, frontend/src/DB/product.json, frontend/src/style/About.css, frontend/src/style/Footer.css
Added whimsical in products.
Kindly comment if any changes needed
#352
=> Added whimsical in products

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/Component/About.js, frontend/src/style/Home.css, frontend/src/style/Navbar.css, package-lock.json, package.json
Added Animations features
Added Animations using vanilla CSS and a using a library data-aos https://michalsnik.github.io/aos/
https://github.com/HimanshuNarware/Devlabs/assets/118285713/61780882-6a9f-4747-8030-10540a62b8c0
=> Animations Added

frontend/src/index.css, frontend/src/index.js, frontend/src/style/Footer.css
#363 
Adding light mode and dark mode theme on the top right side of the page to increase user experience . 
-  [x] Feature enhancement
- [ x] I have performed a self-review of my code
=> #363 solved - added dark mode toggle on top right of page

frontend/src/style/Review.css
This PR is for issue #366 
The text area's was draggable.
I have fixed its size.
The changes I made were in frontend > style > Review.css > for the class-name "input-review"
I have also commented on my changes.
=> Changed the text area.

frontend/package-lock.json, frontend/src/Component/About.js, frontend/src/style/About.css
Style of About Us page such as padding, margin etc.
Change in About Us section
=> updated about

frontend/src/index.js, frontend/src/style/Footer.css, frontend/src/style/Navbar.css
=> Fix: Footer section is not working properly in Dark Mode and Light Mode

frontend/src/style/Home.css, frontend/src/style/Navbar.css
- Done #431 
- Modify the get started button and also done some modification to the search bar
=> Updated get started button

frontend/src/style/Home.css, frontend/src/style/Navbar.css
- Done #438
- Modify all the buttons 
=> Modify buttons

frontend/src/Component/About.js, frontend/src/style/About.css
#447 
Image text overlapping in about US section in mobile view  . by changing CSS styling , I am able to resolve this issue.
before: 
after:-
=> UI issue is fixed in about us section

frontend/src/DB/product.json
-  #385 
- Added new tools in ethical category
- [] I have commented my code, particularly in hard-to-understand areas.
=> Added new tools

.github/workflows/close-on-merge.yml
Fixes #408 
The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.
=> added workflow as mentioned in the issue #408

frontend/src/DB/product.json
This PR is done as per issue #392 
Added the website of hashnode as a dev tool.
=> added hashnode

frontend/src/Component/Sidebar/Sidebar.js, frontend/src/DB/product.json, frontend/src/style/BookMark.css, frontend/src/style/Home.css
- #393 
Add the hover effect to the booked card, similar to other cards
=> Add hover effect to booked card

frontend/src/Component/Sidebar/Sidebar.js, frontend/src/DB/product.json
- #485 
Added the new tools to the collaboration tools category
=> Add new tool

frontend/src/Component/Sidebar/Sidebar.js, frontend/src/DB/product.json, frontend/src/style/Home.css
#486 
Modify the scroll-bar with the existing theme and suitable for dark and light mode
=> Modify scroll bar

frontend/src/style/Review.css
- #459 
Modify the review page the enhance the UI of the page and also change the button hover effect.
=> updated review page

frontend/src/Component/Footer.js, frontend/src/style/Home.css
Resolves #471 
Redirects the social media links in the footer to a new tab
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Redirected social media links to a new tab

frontend/src/style/Home.css
Resolves #474 
Added a custom scroll bar for website enhancement.
- [x ] Feature enhancement
[scroll.webm](https://github.com/HimanshuNarware/Devlabs/assets/116087736/21c5f242-ce07-4fbb-b5ec-001d9b157829)
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Customized scroll bar 

backend/package-lock.json, backend/src/app.js, frontend/src/Component/Home.js, frontend/src/DB/product.json, frontend/src/style/Home.css
Issue No : #492 
I have made changes in  media query in css . 
And also add image in small mobile devices which is looks good.
=> Add responsiveness in Hero section for All devices

frontend/src/index.css, frontend/src/index.js, frontend/src/style/Navbar.css
Navigation bar and padding issue. 
change the padding of toggle button and position of navigation bar because scroll bar is hiding behind the navigation bar and the left padding of toggle button for light and dark mode was 0px.
https://github.com/HimanshuNarware/Devlabs/assets/165997406/53a98b83-6474-418e-a114-88c98acfc632
=> Style change

frontend/src/style/Navbar.css
Issue number #528 
In dark mode navigation bar active cell color is blue which is not good visible. I have changed that.
Before
After
=> navbar color

frontend/src/style/BackToTopButton.css
#538 issue solved
visibled bottom to top button
=> visibled bottom to top button

frontend/src/Component/Home.js, frontend/src/style/Home.css
#520 
Added a "Remove" button functionality to the Home component, allowing users to remove bookmarks from their list. This update includes:
- Implementation of a handleDeleteBookmark function to handle the removal of bookmarks.
- Modification of the Home component to pass the correct productName to the handleDeleteBookmark function.
- Conditional rendering of the "Remove" button and its functionality to update the local storage and state.
- Add PopUp for BookMark Removed.
- Change Styling of removed button
The code is automatically formatted by VS Code for good indentation.
=> Add Directly removed Bookmark from HomePage and also show removed popUp when user removed bookMark

frontend/src/Component/Footer.js
[The spelling of 'Frontend' in your project is currently incorrect as 'Fronted'. By fixing this bug, it will be corrected.  #440]
[The spelling of 'Frontend' was originally incorrect as 'Fronted.' I have corrected it to 'Frontend.' These changes were made in the Footer.js file located within the component folder, which is contained inside the Src folder.]
=> Corrected spelling mistake in Frontend.

frontend/src/DB/product.json
Referring to issue #516 
Added Seowriting in product.json file
I am a gssoc'24 contributor
=> Added new tool seowriting.ai

backend/package-lock.json, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/ChatBot/ActionProvider.jsx, frontend/src/DB/product.json
Enhanced Chatbot Functionality with Activity-based History Storage. #483
This pull request enhances the chatbot functionality by implementing activity-based history storage and adding the feature to close the chat when the user clicks outside of the chatbot area.
https://github.com/HimanshuNarware/Devlabs/assets/142730608/31084322-12d5-47ee-9df5-9098a56f10b2
The changes made ensure that the chat history is stored based on user activity, such as sending messages or receiving responses. Additionally, the chat closes when the user clicks outside of the chatbot area, enhancing usability. Thorough testing has been conducted to ensure the changes work as expected across different scenarios and browsers.
=> Add new feature: enhancement the chat-bot feature

frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx
Added an opening and closing animation on the chatbot when user clicks on chatbot it opens with an animation 
closes : #551 
https://github.com/HimanshuNarware/Devlabs/assets/118350936/8a237b09-4d67-4239-8063-93e24064a6fa
=> Animation on chatbot #551

frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/ScrollToTop.jsx, frontend/src/index.css, frontend/src/index.js
=> fixed scroll to top on render of new page

frontend/src/Component/BackToTopButton.js, frontend/src/Component/Home.js
@panwar8279 
[BUG] : Scroll to top button is not working #582
- i implement logic of back to top button
- when user click on that, they will redirected to hero section [first porion] of website
https://github.com/HimanshuNarware/Devlabs/assets/114583978/d0112eea-55b9-4510-8dad-ef361482e826
=> back to top button done

frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/Navbar/NavbarCenter.js
#570 
Added a contact in navbar
=> Added contact button to navbar and also fixed few errors in other codes

frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/Home.js, frontend/src/style/Home.css
@HimanshuNarware  @panwar8279    I intrigated the contributor section on home page 
fix #588 
**please Mark Gssoc24 and level 3**
- [X ] Feature enhancement
=> added contributor secton

frontend/package-lock.json, frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/Footer.js, frontend/src/index.js, frontend/src/pages/CodingPlateform.jsx, frontend/src/pages/CodingPlatform.jsx, frontend/src/pages/CoursesPlatform.jsx, frontend/src/pages/Extension.jsx
#629 + **Codebase Bug and error fixes**
=> Cleared all the code bugs and also completed #629

frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/Footer.js, frontend/src/Component/Modal.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Rateus.js, frontend/src/index.js, frontend/src/pages/CodingPlatform.jsx, frontend/src/style/Modal.css, frontend/src/style/Navbar.css, frontend/src/style/Rateus.css
Hello Project Admin,
I added a Rate Us Option 
Solved - #652 
Kindly Please go through it
=> Added Rate Us Option

frontend/src/Component/Footer.js
#691
Resolved footer content UI issues
=> Footer content layout change

frontend/src/style/Navbar.css
closes #660 
aligned the contents of the navbar in a single row with proper spacing
=> elements of the navbar are aligned properly in a single row

backend/src/controllers/openSourceController.js
#653 
This pull request addresses the following issues and enhancements:
1. Fixes a typo in the res.status call within the addProject function.
2. Adds validation to ensure required fields (projectName, ownerUsername, link, description) are present in the request body before creating a new project.
3. Returns the created project in the response for the addProject function.
4. Implements pagination in the fetchAllProjects function to handle large datasets efficiently.
5. Enhances error handling and logging for better debugging.
These changes ensure that the addProject and fetchAllProjects functions are more robust, user-friendly, and efficient, particularly when handling large sets of data. This improves the overall reliability and performance of the API.
=> Fix and Enhance Project Management API: Typo Correction, Validation, and Pagination

frontend/src/Component/Home.js, frontend/src/style/About.css
- #707
Removed the contributors from home page and modify the contributors card
=> modify about

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Navbar/NavbarLeft.js, frontend/src/Component/Rateus.js, frontend/src/style/Navbar.css
I Added Icons to Navbar - Solved #700 
Please kindly go through it
=> Added Icons to Navbar

frontend/package-lock.json, frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/Footer.js, frontend/src/index.js
Import issues, closing tag issues, and other issues
Frontend server is able to properly start in the local server
=> Fixed import issues and other syntax issues that wouldn't allow the frontend server to start properly

frontend/src/Component/Rateus.js, frontend/src/style/Rateus.css
I Added toastify message - Solved #702 
https://github.com/HimanshuNarware/Devlabs/assets/161804629/a18029c1-4707-4833-bfc9-bd50f97b2588
=> Added Toastify Message

frontend/public/index.html, frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.jsx
This PR solves two issues at once. One issue is https://github.com/HimanshuNarware/Devlabs/issues/764 and the other is https://github.com/HimanshuNarware/Devlabs/issues/682. Also note that the second issue has been closed by a PA but issue still persists. Please reopen the issue so that I can get the points in GSSoC'24. Thank you.
1) The website name is changed to Devlabs.
2) Fixed the errors in App.js
3) Fixed one error in ChatAssistant.jsx
4) Fixed the deployment issue (Hopefully).
=> Changed the website name and fixed App.js 

backend/.dockerignore, backend/Dockerfile, compose.yaml, frontend/.dockerignore, frontend/Dockerfile, frontend/src/App.js, frontend/src/ChatAssistant/Avatar.jsx, frontend/src/ChatAssistant/UserAvatar.jsx, frontend/src/Component/About.js, frontend/src/Component/Footer.js, frontend/src/index.js
Closes [#768](https://github.com/HimanshuNarware/Devlabs/issues/768)
The Dockerfile, .dockerignore have been added to both the backend and frontend folder. A docker compose file has been added in the root folder. The rest of the changes were the rectification of errors in some files which was hindering the build process. 
None
Please do add the gssoc label.
Please do add the necessary label.
=> Added containerization files for both frontend and backend

frontend/src/ChatAssistant/ChatAssistant.css
fixes #835 
Now the input of chatbox is properly visible
=> Fixed input of chatbox

frontend/src/ChatAssistant/ChatAssistant.css
Reverts HimanshuNarware/Devlabs#844
=> Revert "Fixed input of chatbox"

frontend/src/App.js, frontend/src/Component/Footer.js, frontend/src/DB/product.json, frontend/src/index.js
#745 
added new tool iconfinder
=> Icon finder

frontend/src/App.js, frontend/src/index.js, frontend/src/style/Courses.css, frontend/src/style/Navbar.css
Hello Project Admin,
=> I Decreased the size of Navbar and Avoided Collision between Nav Items and Search Bar - Solved #838 
Kindly Please go through it @panwar8279 
https://github.com/HimanshuNarware/Devlabs/assets/161804629/e1fe69f4-72fd-4a13-aee6-4706ad7b6d50
=> Enhanced Navbar and Removed Repeated Content

frontend/src/DB/product.json
#727 
SQL Police Department is an online game where you solve crimes using SQL (and learn SQL in the process). Learn SQL while playing a game!
=> SQL PD Tool Added

frontend/src/DB/product.json
issue : #880 
The tool coded pad add tool the project it is very useful for storing and retrieving the text information when required without any sign in or login in> for strong of text information it is very useful tool.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/4c65a329-131d-4887-b1d8-430067800853
I PR the assigned issue please check my changes and merge the changes @panwar8279 and @HimanshuNarware to make contribution to the project.
Thank you
=> Tools: Coded Pad too added

frontend/src/DB/product.json
Closes: #609 
Added a new tool 1337x to download Games, Movies, Documentaries etc. for Free
https://github.com/HimanshuNarware/Devlabs/assets/118066299/39601eba-3cfe-4028-8032-df8a23c09e5f
=> Added 1337x Website

frontend/src/DB/product.json, frontend/src/style/Rateus.css
- #714
Modify the rate us page as per the theme of the web page
- [] Feature enhancement
- [] Documentation update
- [] Other (specify): _______________
- [] I have commented my code, particularly in hard-to-understand areas.
=> Modify Rate us

frontend/src/Component/About.js, frontend/src/Component/Pagination.js, frontend/src/utils/paginationData.js
… 
closes #472
remove bug while performing prev and next button in pagination
https://github.com/HimanshuNarware/Devlabs/assets/140513098/882f3d2e-0554-4053-ad23-4d09712681f1
https://github.com/HimanshuNarware/Devlabs/assets/140513098/1136e4b2-1148-4df1-8cab-ed2405deff08
i also remove prev button for page 1 and next button remove in last page
=> Add condition for pagination and also remove prev and next button for first and last page

frontend/src/DB/product.json
#isssue : #917 
It is an AI tool used to generate the video from text we can edit it , download it , add subtitles and more.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/b8ca74f9-9622-439e-8b2e-eb69e70c288f
I PR the issue check the changes and merge the changes to make contribution to the project @HimanshuNarware and @panwar8279
=> Invideo Ai tool added to the project

frontend/src/Component/Review.js
fixes #899 
Added feedback type. If user chose the "other" option, he/she would have to specify the topic.
=> Feedback type

frontend/src/ChatAssistant/ChatAssistant.css, node_modules/.package-lock.json
Hi @HimanshuNarware & @panwar8279  ,
closes #963
******Video/Screenshots (mandatory)******
Here as you can see :
https://github.com/HimanshuNarware/Devlabs/assets/160386036/3115e6a2-41ca-4146-9171-bae6263e221e
Please take a look and also add required labels.
=> Resolved overlapping between chatbot and scroll-to-top button

frontend/src/App.css, frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/Component/TrailingCursor/TrailingCursor.jsx, frontend/src/Component/TrailingCursor/TrailingCursor.module.css, frontend/src/index.css, frontend/src/style/About.css, frontend/src/style/BackToTopButton.css, frontend/src/style/BookMark.css, frontend/src/style/Footer.css, frontend/src/style/Home.css, frontend/src/style/Modal.css, frontend/src/style/Navbar.css, frontend/src/style/NotFound.css, frontend/src/style/Rateus.css
closes : #732 
add the customized mouse movement for the cursor,A trailing effect adds for the cursor while moving through out the page
https://github.com/HimanshuNarware/Devlabs/assets/125206920/911bfbfe-5912-4f6e-a8fb-bc51140badd2
https://github.com/HimanshuNarware/Devlabs/assets/125206920/a2a95043-87c0-42ef-af1c-05fc21311258
=> Trailing cursor

frontend/src/DB/product.json
#1002 
LinkedIn profile optimization, AI generated cover letters, auto-fill and track job applications, resumes, and more!
- [] Documentation update
- [] Other (specify): _______________
https://github.com/HimanshuNarware/Devlabs/assets/108017771/0275ad35-fa1c-4714-b631-ddef92bbf93b
=> careerflow ai extension added

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/Component/Contact.jsx, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/style/Contact.css
As before contact us page redirects to linkedin we can make users to stay on site.
Created a seperate page for contact us
[Screencast from 2024-06-19 07-30-54.webm](https://github.com/HimanshuNarware/Devlabs/assets/71129858/1a3e0f33-eb0a-48d2-b117-97185f5a3d7d)
Resolves #937 
Please close under GSSOC'24 level 3 as labeled in issue.
=> Seperate page for contact us

frontend/src/DB/product.json
Fixes #950 
I don't know how, but we added duplicate tools during another PR merge.
=> Duplicate tools removed

README.md
#842 
i added techstack logo
- [ x] Documentation update
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Update README.md #842

frontend/src/style/Navbar.css
=> search box position fixed there relative position

frontend/src/Component/Sidebar/Sidebar.js
Fixes #872 
A unique `key` prop for each element is essential in the' Sidebar' component. It helps React identify changes, additions, or removals in the list, optimizing re-rendering and improving performance. This prevents bugs and ensures smooth updates within the sidebar.
**BEFORE**
https://github.com/HimanshuNarware/Devlabs/assets/105718863/9ce7c030-e878-4c23-94ac-96ef85f36a88
**AFTER** - We can see in the console the error has been resolved and the sidebr is functional
https://github.com/HimanshuNarware/Devlabs/assets/105718863/373b36e0-d33b-48b8-917d-46c85b5dc486
=> Unique Key Prop in Sidebar

frontend/src/DB/product.json
=> programiz added

frontend/src/DB/product.json
added jupyter lab in devlabs
issue #368 
added jupyterlab in devlabs
NIL
NIL
=> Update product.json as per issue#368

frontend/src/DB/product.json
=> docker added

frontend/src/DB/product.json
=> github copilot added

frontend/src/DB/product.json
=> gemini added

frontend/src/DB/product.json
Collection of cheet sheet of multiple techs
https://github.com/HimanshuNarware/Devlabs/assets/124615886/b6232eea-8878-403e-a3cb-7b7379da53f9
=> Added over api cheet sheet

frontend/src/DB/product.json
Showcase yourself to a curated list of top companies
Complete privacy and no spam
https://github.com/HimanshuNarware/Devlabs/assets/124615886/6fd69e24-9ba2-4a81-921a-7954ad3d86ef
=> Insta Hire

frontend/src/pages/FrontendTools.jsx
Next.js framework in FrontendTools page added
https://github.com/HimanshuNarware/Devlabs/assets/125860170/c8313c56-38e4-4088-b001-8c3d8ab4a649
=> Next.js framework in FrontendTools page

frontend/src/DB/product.json
Relight your photos & drawings in seconds
https://github.com/HimanshuNarware/Devlabs/assets/124615886/12ae0720-5f23-4416-86d7-4b6c52ea7de2
=> Added Relight image editing tool

frontend/src/DB/product.json
Every tool you could want to edit images in bulk
https://github.com/HimanshuNarware/Devlabs/assets/124615886/737aa36e-1099-48dd-9db2-5419636d8641
=> Added I love img tool

frontend/src/DB/product.json
One Library All of India. The national digital library of India
https://github.com/HimanshuNarware/Devlabs/assets/124615886/a0c575cb-9e3d-41d9-a447-05805db7f980
=> Tool National library of India

frontend/package.json, frontend/src/Component/Home.js
I have added the tilt effect on the header image 
closes : #876
https://github.com/HimanshuNarware/Devlabs/assets/118350936/71e52f8f-a368-4d03-a871-d262f06839e2
=> Added tilt effect

frontend/src/DB/product.json
Unsplash is a free internet source for visuals images
https://github.com/HimanshuNarware/Devlabs/assets/124615886/937fe12c-c512-4560-976b-f71146ae3f95
=> Tool Unsplash free stack visuals

frontend/src/style/Home.css
I have added the 3d card effect on the cards 
closes : #896 
https://github.com/HimanshuNarware/Devlabs/assets/118350936/d3f3b545-77aa-4950-90aa-67baec194860
=> Added 3d card Effect

frontend/src/DB/product.json
#746 
- [x ] Feature enhancement
- [ x] I have performed a self-review of my code
=> add jasper ai

frontend/src/DB/product.json
=> add vercelTool

frontend/src/style/CodingPlatform.css
I enhanced the coding platform page 
closes : #983 
https://github.com/HimanshuNarware/Devlabs/assets/118350936/45688c59-b793-42da-9725-204f380c5293
=> Enhancement of coding platform page

frontend/src/DB/product.json
=> add spline3d tool

frontend/src/pages/FrontendTools.jsx
ADD Bulma in front-end-tools page
https://github.com/HimanshuNarware/Devlabs/assets/125860170/57ee1c8f-6e0b-4040-97f1-89d43d722eed
=> ADD Bulma in front-end-tools

frontend/src/pages/FrontendTools.jsx
I have added the foundation Tool for the website .
closes : #1006 
=> Added Foundation Tool

frontend/src/DB/product.json
Added the tool Aceternity UI
https://github.com/HimanshuNarware/Devlabs/assets/124615886/24aecd40-5b4f-4b0d-be08-235992e7a8db
=> added the tool Aceternity UI

frontend/src/DB/product.json
[New Tool]: Want to Add Array Explorer #1137
A resource to help figure out what JavaScript array method would be best to use at any given time
- [y ] Feature enhancement
- [ X] I have commented my code, particularly in hard-to-understand areas.
https://github.com/HimanshuNarware/Devlabs/assets/101548649/453b7b9e-7796-4e03-9a9a-34dc1f0e33b6
=> [New Tool]: Want to Add Array Explorer #1137

frontend/src/Component/Footer.js, frontend/src/Component/TrailingCursor/TrailingCursor.jsx
#628 
Added "Contribute Here" in the footer
https://github.com/HimanshuNarware/Devlabs/assets/126975547/0eda64e0-52bd-4b5f-a87d-653a1afbe824
=> added contribute here and other links

frontend/src/DB/product.json
issue : #1144 
FreeConvert's video compressor is a user-friendly tool that helps you reduce the file size of your videos without compromising on quality. This tool is added to the project
https://github.com/HimanshuNarware/Devlabs/assets/124431955/6d1f320b-4521-4607-b5fe-b6ca88a9da7d
@HimanshuNarware and @panwar8279 I have completed the assigned issue. Please review my changes and merge them into the project to contribute to the project.
Thank you
=> Video Compressor added to project

frontend/src/Component/Footer.js
Closes #614
This pull request adds a "Sponsor Me on GitHub" button to the footer component of the website. The button is placed below the "MAINTAINED BY HIMANSHU NARWARE" text and above the social media icons. The button links to the GitHub sponsors page and includes an image badge for visual appeal.
Feature enhancement
✔ I have performed a self-review of my code.
✔ I have read and followed the Contribution Guidelines.
✔ I have tested the changes thoroughly before submitting this pull request.
✔ I have provided relevant issue numbers, screenshots, and videos after making the changes.
✔ I have commented my code, particularly in hard-to-understand areas.
The "Sponsor Me on GitHub" button provides a direct link for users to support the project via GitHub Sponsors.
=> Sponsor me button added #614

frontend/src/DB/product.json
Closes issue: #1199 
I have added the perplexity AI.
Kindly let me know if there are any changes to be made.
=> perplexity ai added

frontend/src/App.js, frontend/src/pages/Collaboration.jsx, frontend/src/style/Collaboration.css
Solves #1209
I have added contents on the collaboration tools page and also removed the 4040 page not found error.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/3b95263b-5469-4327-a3a7-749e0d749a8a
=> Removed the 404 error and added contents on the collaboration tools page.

frontend/src/DB/product.json
Closes issue : #1181 
I've added GSSoC.
[Attach any relevant screenshots or videos demonstrating the [changes]](
https://github.com/HimanshuNarware/Devlabs/assets/101091762/2045cfb6-7094-4a28-9021-1c710a462c5b
)
Kindly let me know if there are any changes to be made.
=> Added GSSoC

frontend/src/DB/product.json
=> Google colab

frontend/src/DB/product.json
=> Added Babbel

frontend/src/DB/product.json
#1090
I have added linkedin learning
=> Added Linkedin learing

frontend/src/Component/Home.js, frontend/src/style/Home.css
Fixed the hero section to be responsive on all devices...
=> fixed hero section to be responsive

frontend/src/DB/product.json
#1089
I have added skill share
=> Added Skill share

frontend/src/DB/openSource.json
issue #1000
Blockchain Supply chain management plays a critical role in ensuring efficient operations and maintaining consumer trust. This project focuses on developing and deploying a decentralized application (DApp) powered by blockchain technology to streamline supply chain management processes.
=> ADD Supply Chain Management DApp

frontend/src/DB/product.json, frontend/src/pages/UI.jsx, frontend/src/style/UI.css
Solves #1114
I have added contents on the UI page along with styling and animations and now it looks like other pages.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/65523565-a53d-46e4-a29b-9ec3ccbf859b
=> Added contents on UI page.

frontend/src/DB/openSource.json, frontend/src/pages/CodingPlatform.jsx
=> [New Tool]: programiz Coding Platforms

frontend/src/DB/product.json
=> Added Edabit

frontend/src/DB/product.json
Closes #1115 
Added a video downloader -
Download videos from the web. Easy, smart, no tracking.
- Video Download: 1000+ websites supported (Dash, HLS, MPD, …)
- Live Stream Support: Enjoy offline viewing of live streams, freeing you from real-time constraints.
- HD Download and Conversion: Download videos in high-definition and convert them to your preferred formats (MP4, MKV, WebM, …) for optimal viewing pleasure
- Audio Download: Extract audio from videos, converting them into MP3s or podcasts for easy listening.
=> Added Video Downloader

frontend/src/DB/product.json
Closes issue: #1197 
I have added runaway ai in products.json file.
https://github.com/HimanshuNarware/Devlabs/assets/131477601/e4eeaec6-4070-4bc0-9d91-672c8b580dbd
It is not allowing me to add a 30sec demo video:
=> runaway ai is added

frontend/src/DB/product.json
Closes issue: #1198 
I have added the stability ai tool in products.json file
=> stability ai added

frontend/src/pages/FrontendTools.jsx
[New Tool]: Adding Grommet tool in frontend Tools #1173
- [X ] Feature enhancement
Added grommet tool 
- [ X] I have read and followed the Contribution Guidelines.
- [ X] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ X] I have commented my code, particularly in hard-to-understand areas.
=> [New Tool]: Adding Grommet tool in frontend Tools #1173

frontend/src/App.js, frontend/src/pages/Productivity.jsx, frontend/src/style/Productivity.css
Solves #1207
I have added contents on the productivity tools page and removed the 404 not found error page.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/dc149024-367f-49b6-b2e0-22f9a389b403
=> Removed the error and added contents on the productivity tools page.

frontend/src/style/Navbar.css
fixed issue Over-width navbar  #1215
Here's the video proof of navbar issue fix:
https://github.com/HimanshuNarware/Devlabs/assets/114223066/84bc6e4c-305e-476e-9c3c-602cb143ad2f
=> Fixed the navbar overflow of contents

frontend/src/Component/Footer.js
issue : #1103 
logo and description added correctly with proper alignment and effects.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/925300f9-becb-43f3-9d4a-045f07e46519
@HimanshuNarware  and  @panwar8279  please check my changes and merge to project to make contribution.
Thank you
=> Feature :Descrition and logo added

frontend/src/DB/product.json, frontend/src/style/Review.css
closes: #1021 
Text in the review is not appearing to the users so I fixed it by changing the font styling like font size, color, weight, letter spacing, etc and also updated the CSS of the review form for optimal user experience.
https://github.com/HimanshuNarware/Devlabs/assets/125206920/e73301bd-afb0-4c2a-811b-f1378a2d4413
=> Form update

frontend/src/DB/product.json
#1096 
Bollyflix is a popular website to download movies, webshows, anime and much more.
=> Added Bollyflix

frontend/src/DB/product.json
#1100 
HiAnime.to is a very popular free site to watch anime
=> Added HiAnime

frontend/src/DB/product.json
#1099
123Movies is a popular website to stream movies, webshows, anime and much more.
=> Added 123Movies

frontend/src/DB/product.json
#1098 
1Flix is one of the most visited sites for free movie streaming.
=> Added 1Flix

frontend/src/DB/product.json
issue #673 
Added GitLab into devlabs
NIL
NIL
=> Added GitLab

frontend/src/DB/product.json
added jupyternotebook
issue#671
added jupyter notebook
NIL
NIL
=> Update product.json as per issue#671

frontend/src/DB/product.json
#1097 
Binged is a popular website to stream movies, webshows, anime and much more.
=> Added Binged

frontend/src/DB/product.json
issue #672 
Added Udemy into devlabs
NIL
NIL
=> Added Udemy to devlabs

frontend/src/Component/Home.js, frontend/src/style/Home.css
Fixes #767 
I have added a category-based sorting feature, as we are growing in the number of tools. We can help users to sort some tools based on categories like resume, coding, AI, remote, etc.
https://github.com/HimanshuNarware/Devlabs/assets/105718863/3cb632fd-0c26-4a63-a392-0028f3265d8e
Hello @panwar8279, This is my third PR on the same issue, I have solved all the merge conflicts. Please merge as soon as possible. If possible merge this PR at first, so it does not encounter any merge conflicts
=> [ IMP FEATURE ] Category sorting

frontend/src/DB/product.json
closes issue: #1278 
I have added forage
Kindly review this PR.
=> forage added

frontend/src/DB/product.json
closes issue: #1196 
I have added zoom.
once please review this PR.
=> zoom added

frontend/src/DB/product.json
Closes issue: #1310 
I have added the sharly AI
=> sharly added

frontend/src/DB/product.json
Closes issue: #1311 
I have added the Leonardo AI
kindly let me know if there are any changes to be made.
=> Leonardo AI added

frontend/src/DB/openSource.json
issue #1293
This platform helps people adopt pets and if they want to migrate from the country, they place their dog on this platform and others adopt them.
=> ADD petAdopt opensource

frontend/src/pages/CodingPlatform.jsx
#1014
added leetcode and codechef
=> added leetcode and codechef

frontend/src/pages/FrontendTools.jsx
closes #1017
Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.
=> sass added

frontend/src/DB/product.json
Closes issue: #1308 
I have added the warmer ai tool
=> Warmer  AI added

frontend/src/DB/product.json
Closes issue: #1309 
I have added the Akkio ai tool
=> Akkio AI added

frontend/src/DB/product.json
added quira into devlabs
issue #1327
added quira into devlabs
NIL
NIL
=> Added Quira

frontend/src/DB/product.json
added quora into devlabs
issue #1365
added quora
NIL
NIL
=> Added Quora digest

frontend/src/Component/Faq.js, frontend/src/index.css, frontend/src/style/Home.css, frontend/src/style/Navbar.css
#1333 
Made everything responsive to have a good user experience...
=> Made website responsive for alll devices

frontend/src/Component/Faq.js, frontend/src/DB/product.json
#1334 
Added the new tool image color picker and fixed the error of FAQ component 
https://github.com/HimanshuNarware/Devlabs/assets/124615886/c2077f81-2993-49d9-a89e-5b8406f254a3
=> Added new tool image color picker and fixed FAQ error

frontend/src/Component/Faq.js, frontend/src/DB/product.json
#1358 
Added new tool Brime also fixed the issue with FAQ component that was creating problem in build...
https://github.com/HimanshuNarware/Devlabs/assets/124615886/81623a14-86c0-411d-a02e-189d33a49583
=> Added new tool Brime to Bulk resize the images

frontend/src/style/BackToTopButton.css
=> back to top button

frontend/src/DB/product.json
fixed #1261 
Microsoft SQL Server is a relational database management system. As a database server that stores and retrieves data as requested by other software applications on the same computer or a remote computer using the client-server model. Microsoft provides APIs to access SQL Server over the internet as a web service.
=> added SQL server in tools

frontend/src/Component/Footer.js, frontend/src/style/Footer.css, frontend/src/style/Navbar.css
=> updated footer issue

frontend/src/style/Navbar.css
=> fixed issue #1344

frontend/src/pages/FrontendTools.jsx
fixed #1260 
Added TypeScript as new tool on frontend-Tools for frontend technologies
=> Added TypeScript as new tool on frontend-Tools

frontend/src/App.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/pages/BackendTools.jsx, frontend/src/style/BackendTools.css
Fixes #1361
I have added a new page backend tools and also added the major backend tools used today. I have also added relevant styling and animations in this page.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/e7eeab97-cbf8-49cb-98bf-4860aa93c3b4
=> backcommit

frontend/src/DB/product.json
issue#1326
added flutterflow
NIL
NIL
=> Added FlutterFlow into devlabs

frontend/src/DB/product.json
Added remove .bg into devlabs
issue #1367 
added remove.bg 
NIL
NIL
=> Added background remover

frontend/src/DB/product.json
issue #1369 
added fotor into devlabs
NIL
NIL
=> Added Fotor into devlabs

frontend/src/DB/product.json
issue #1330 
added skillsnetwork lab into devlabs
NIL
NIL
=> Added SkillsNetwork Lab

frontend/src/DB/product.json
Added Shutterstock into devlabs
issue #1368 
added shutterstock into devlabs
NIL
NIL
=> Added Shutterstock

frontend/src/DB/product.json
#1288 
Animetsu is a free Anime watching platform.
=> Added Animetsu

frontend/src/DB/product.json
Fixes #1236 
Added Listly - Web Scraping Extension
=> Added Listly - Web Scraping

frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/Component/BackToTopButton.js, frontend/src/style/BackToTopButton.css
#1062 
#1062 
https://github.com/HimanshuNarware/Devlabs/assets/109097899/fb31f10e-ceed-43ad-bda7-d5b9db27a03a
Sorry to say that i am unable to add tooltip on theme icon
=> add tooltip

frontend/src/pages/Extension.jsx
#1306
Now the Extensions heading is clearly visible on the Extensions page.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/7d49644d-0f00-46c5-b09a-029b2ceee5e6
=> Extension heading is now visible on the Extensions page.

frontend/src/DB/product.json
Closes issue: #1356 
Fiverr added.
=> fiverr added

frontend/src/DB/product.json
Closes issue: #1353 
Deep AI added.
=> deep ai added

frontend/src/DB/product.json
Closes issue: #1251 
lucid chart added.
=> lucid chart added

frontend/src/DB/product.json
Closes issue: #1252
sublime text added
=> sublime text added

frontend/src/DB/product.json
Closes issue: #1352 
I have added the cohere AI
=> cohere ai added

frontend/src/Component/Review.js, frontend/src/pages/UI.jsx, frontend/src/style/UI.css
@panwar8279 
[Feature Request]: Add Toast Message when user submit review #1266
close #1266
- added toast message on review form
=> Toast review form

frontend/src/pages/UI.jsx, frontend/src/style/UI.css
@panwar8279 
[Feature Request]: Add UI Page #1265
close #1265
- Update UI page code
- make it responsive
- fixing style of ui page
=> update ui page

frontend/src/Component/Sidebar/Sidebar.js, frontend/src/pages/CoursesPlatform.jsx
#1240
#1360
Added contents on the courses platform page and removed the 404 error page . 
https://github.com/HimanshuNarware/Devlabs/assets/143121854/de767adf-c260-459d-8eb6-df3a48734deb
=> Added contents on the courses platform page and removed the 404 error page.

frontend/src/DB/product.json
issue  : #1168 
Coded Pen platform added to website, An online code editor and social development environment for front-end developers to build and share web projects.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/aef0a0d7-6afb-47ca-ae57-e943a7268a4d
@HimanshuNarware  and @panwar8279 , I PR the issue again due to conflicts of previous PR #1301 ,   so please check my changes and merge to project.
Thank you
=> NewTool : Coded pen added to project

frontend/src/Component/Footer.js, frontend/src/Component/Home.js, frontend/src/style/Footer.css, frontend/src/style/Home.css, frontend/src/style/Navbar.css
On the home page, there is a minor mistake that is making the website look unprofessional. The issues include:
-The navbar content does not show the line properly when hovering.
-The black color for the filter button does not enhance the website's appearance.
-pagination is not proper set
-footer alignment is not good.
All issues have been resolved, and this is ready for merging.
https://github.com/HimanshuNarware/Devlabs/assets/115735153/3ac9623b-4953-4925-a2f4-fcfcdd669c84
I am a GSSOC Contributor.
=> Modify home page all issues

frontend/src/pages/Movie.jsx
#1370 
#1305
Corrected the contents of the movie and series page added with appropriate styling and animations.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/0e5dabd8-8ae4-46b2-a8bd-3ed5dc1a2f1d
=> Corrected the contents of Movie & Series page.

frontend/src/App.js
fixes #1468 
Implmented lazy loading using React.lazy which lets you render a dynamic import as a regular component. This is used to load the components only when they are needed.
=> Efficiency Enhancement

frontend/src/pages/Extension.jsx
#1441
Trained on GPT-3, GitHub Copilot gives code suggestions, auto-completes code, and can even help write code when you provide a natural language comment.
=> Added Copilot in Extension

frontend/src/style/Navbar.css
#1323 
In the footer, I added a very smooth hover effect that gently highlights elements when you move your cursor over them. This effect provides a subtle visual feedback, enhancing user interaction.
https://github.com/HimanshuNarware/Devlabs/assets/95361125/99bc3864-c5e1-40e8-8983-6300b9eb461b
Close Issue : #1323
=> Footer-Hover Updated

frontend/src/DB/product.json
Fixes #1349 
Added Research AI
=> Added Research AI

frontend/src/Component/OpenSource.js, frontend/src/style/About.css, frontend/src/style/OpenSource.css
The issue is that the open-source page grid structure is not perfect and not responsive, which is why the website is not looking cool.
in open source page grid structure fits perfectly and makes it responsive.
https://github.com/HimanshuNarware/Devlabs/assets/115735153/9af1f2b9-2eac-4974-9924-33d9e24f0d4e
I am a GSSOC Contributor.
=> modify opensource page and responsive also

frontend/src/DB/product.json
issue : #1335 
Play code web development platform is added to the project.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/075d95c5-03fa-4e71-96ee-82eb41a41cef
@HimanshuNarware  and @panwar8279  , please check the changes and merge the changes to the project to make contribution to the project.
Thanking  you
=> NewTool: Play Code Platform is added to the Project

frontend/src/pages/CodingPlatform.jsx
close #1418
HackerRank is the market-leading coding test and interview solution for hiring developers. Start hiring at the pace of innovation! helps companies develop the strongest tech teams around. We help candidates sharpen their tech skills and pursue job opportunities.
=> hackerrank coding platform 

frontend/src/Component/About.js, frontend/src/style/About.css
#1402 
The contributors section was overlapping previously and having white gate at right side .i have fixed and redisgned with proper alignment 
https://github.com/HimanshuNarware/Devlabs/assets/122633300/c258bf4d-457c-4706-9d84-5c439490dadb
=> Contributor section design fixed

frontend/src/Component/Home.js, frontend/src/style/Home.css
Fixes #1110 
Used a react useState to display an input field above the sorting field. OnChange on input calls a function, and that function makes comparison with the josnTools and displays is at results
https://github.com/HimanshuNarware/Devlabs/assets/105718863/d37f7bf5-e1d0-42eb-9fe5-c76ac3e66077
=> [ IMP FEATURE ] : Search Bar Functionality 

frontend/src/DB/product.json
Closes issue: #1399 
Synthesia added.
=> synthesia added

frontend/src/DB/product.json
Closes issue: #1398 
Descript AI added.
=> descript ai added

frontend/src/DB/product.json
Closes issue: #1397 
Freelancer added
=> freelancer added

frontend/src/style/OpenSource.css
#1401 
The opensource page cards were not proper ,I have redesigned and aligned them properly.
I have used grid to align 3 cards in each row
I have added bottom in hover effect also.
https://github.com/HimanshuNarware/Devlabs/assets/122633300/a24ac744-be10-4eea-ae67-f660f47cb8fa
=> Open Source page redesigned

frontend/src/DB/product.json
=> Algomonster added

frontend/src/style/About.css
Issue number : #1470 
https://github.com/user-attachments/assets/6a0bda0c-d363-485b-a9ea-d7012f4102cb
=> Made contributor section responsive and also structured components of contributor section

frontend/src/DB/product.json
Closes issue: #1396
I have added the learn git branching tool.
=> learn git branching added

frontend/src/DB/product.json
Closes issue: #1394
I have added lovo AI.
=> lovo ai added

frontend/src/DB/product.json
Closes issue: #1392 
Llama AI added
=> llama ai added

frontend/src/DB/product.json
Closes issue: #1391 
Awwwards website added.
=> awwwards added

frontend/src/style/BookMark.css, frontend/src/style/Contact.css
- #1436 
Fix the text visibility issue of the book-marked card text
=> Fix booked card

frontend/src/pages/BackendTools.jsx
fixed #1465 
Added RubyOnRails for backend Tools
=> Added RubyOnRails for backend Tools

frontend/src/pages/BackendTools.jsx
fixed #1463
Added .Net technology tool for backend tools
=> Added .Net technology tool for backend tools

frontend/src/style/BookMark.css
fixes #1469 
https://github.com/HimanshuNarware/Devlabs/assets/114223066/ed40fcb6-331f-4724-b7ec-8a5dbe389ec9
=> fixes #1469

frontend/src/DB/product.json
Fixes #1350 
Added Engage AI- Chatgpt for Social Media
=> Added Engage AI

frontend/src/pages/AI.jsx
#1384
The AI Blog is now properly visible on the AI page.
https://github.com/HimanshuNarware/Devlabs/assets/143121854/bc3bd86d-7c30-4a54-89a5-69eed3cdff6c
=> AI Blog heading is now visible on the page .

frontend/src/pages/CodingPlatform.jsx
closes #1424
A portal for computer science resources, tutorials, and coding practice
=> geeksforgeeks added in coding platforms page

frontend/src/Component/Footer.js, frontend/src/style/Footer.css
issue : #1102 
Added the hovering and background effects to the icons.
https://github.com/HimanshuNarware/Devlabs/assets/124431955/1cee6e23-e922-4bc9-8a9d-067537ad3923
@HimanshuNarware  and @panwar8279 , please check my changes and merge the changes to the project to make contribution to the project.
=> Title: Hovering effect added to the icons

frontend/src/DB/product.json
Added Postman
Issue#1413
Added postman into devlabs
NIL
NIL
=> Added Postman

frontend/src/DB/product.json
Added foss united
Issue #1414
added foss united into devlabs
NIL
NIL
=> Added FOSS United

frontend/src/DB/product.json
added icfoss
Issue#1415
added ICFOSS
NIL
NIL
=> Added ICFOSS

frontend/src/DB/product.json
Added element
Issue#1417
added element 
NIL
NIL
=> Added element

frontend/src/DB/product.json
Added simplilearn
Issue#1448
added simplilearn
NIL
NIL
=> Added Simplilearn

frontend/src/DB/product.json
Issue#1450
added dailymotion
NIL
NIL
=> Added Dailymotion

frontend/src/DB/product.json
=> Added deepbrain ai

frontend/src/DB/product.json
Issue #1452
added invideo
NIL
NIL
=> Added invideo

frontend/src/DB/product.json
=> Added pluralsight

frontend/src/DB/product.json
issue #1455
added moodle
NIL
NIL
=> Added moodle

frontend/src/DB/product.json
issue #1457 
added mulearn
NIL
NIL
=> Added mulearn

frontend/src/DB/product.json
issue #1458 
added ieee
NIL
NIL
=> Added IEEE

frontend/src/DB/product.json
issue #1459 
added studocu
NIL
NIL
=> Added Studocu

frontend/src/style/BackToTopButton.css
Solved issue #1423 
Removed the overlapping of buttons for smaller screens.
Before:
After:
Even after clicking the button , overlapping is removed.
=> Removed the Overlappings

frontend/src/Component/Footer.js, frontend/src/style/Footer.css
Fixed issue #1596 
Added the hover effects on social media icons
Uploading DEVLABS - Google Chrome 2024-07-12 13-24-17 (online-video-cutter.com).mp4…
=> Created the social icon hover effect of footer

frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/ChatBot/config.jsx, frontend/src/style/Navbar.css
fix issue #1607
I have resolved the problem.
https://github.com/user-attachments/assets/456c934a-2247-4817-ad2e-cbba033c3569
I'm a GSSOC Contributor.
=> modify chatbot and remove bug

README.md, backend/Dockerfile, docker-compose.yaml, frontend/Dockerfile
#1422 
Corrected the Dockerfile for the backend and updated the docker-compose file. Also updated the readme required for the installation using docker.
=> Integrated dockerfile into the project

frontend/src/DB/product.json
issue : #1485 
It is an movies streaming platform where user can view the movies online and even download it.
https://github.com/user-attachments/assets/dadc5d9b-e658-4a64-905d-ff765c8f399c
@HimanshuNarware and @panwar8279 , please check my changes and merge the changes to make contribution to the project.
Thank you
=> NewTool: ibomma added to website

frontend/src/DB/product.json
issue : #1488 
Amazon prime video is added to the website  , it is an movies streaming platform user can view the videos offline as well as online.
https://github.com/user-attachments/assets/9694d0ca-7a1b-4f70-b4de-11417d32b23e
- X] I have read and followed the Contribution Guidelines.
@HimanshuNarware  and @panwar8279 ,please check my changes and merge the changes to the project to make contribution to the project.
Thank you
=> Title:- Amazon Prime Video Added

frontend/src/Component/Footer.js, frontend/src/pages/Extension.jsx, frontend/src/pages/FrontendTools.jsx, frontend/src/pages/Movie.jsx, frontend/src/style/Footer.css
Added Rateus on Footer and also alligned Footer Perfectly - Solved #1523 
Kindly Please go through this PR @panwar8279
=> Added Rateus and Alligned Footer 

frontend/src/Component/Footer.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Navbar/NavbarLeft.js, frontend/src/Component/Navbar/NavbarRight.js, frontend/src/Component/NotFound.js, frontend/src/Component/Review.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/pages/Extension.jsx, frontend/src/pages/FrontendTools.jsx, frontend/src/pages/Movie.jsx, frontend/src/style/Footer.css
I Fixed Mobile view and also removed Unncessary Overlapping - Solved #1146 
Kindly Please go through this PR @panwar8279 
https://github.com/user-attachments/assets/4006c644-361c-4eb1-b63e-9641d1dfaf2d
=> Fixed Mobile view

frontend/src/pages/CodingPlatform.jsx
fixes #1554 
Added kaggle coding platform
=> Add Kaggle coding platform 

frontend/src/pages/CodingPlatform.jsx
fixes #1555 
Adding Top coder in coding platforms
=> Add top coder in coding platform

frontend/src/DB/product.json
fixes #1645 
add vs code in tools section 
=> add vs code

frontend/src/pages/CodingPlatform.jsx
=> add codeforces coading platform

frontend/src/DB/product.json
Added Lumosity
Issue #1610 
Added Lumosity
NIL
NIL
=> Added Lumosity

frontend/src/DB/product.json
Added Appsumo
Issue #1532
Added Appsumo
NIL
NIL
=> Added Appsumo

frontend/src/DB/product.json
Added Metamask
Issue #1531 
Added Metamask
NIL
NIL
=> Added Metamask

frontend/src/DB/product.json
Added Glen world
Issue #1530 
Added Glen world
NIL
NIL
=> Added Glen world

frontend/src/DB/product.json
Added British council learn english
Issue #1529 
Added British council learn english
NIL
NIL
=> Added British council learn english

frontend/src/DB/product.json
Added nasa space app challenges
Issue #1528 
addd nasa space apps challenge
NIL
NIL
=> Added NASA Space Apps Challenge

frontend/src/DB/product.json
added coin market cap
Issue #1527 
added coinmarket cap
NIL
NIL
=> Added CoinMarket Cap

frontend/src/DB/product.json
Added Kucoin
Issue #1526 
addd kucoin
NIL
NIL
=> Added KuCoin

frontend/src/DB/product.json
issue : #1633 
The Ninja AI is a stealthy and agile artificial intelligence designed to assist users with quick and efficient tasks.
https://github.com/user-attachments/assets/4fcf68f2-a7fe-4a57-ab9e-31dc6afc46da
@HimanshuNarware  and @panwar8279 , please check my changes and merge the changes to make contribution to the project.
Thank you
=> Title:- Ninja Ai platform added to the Website

frontend/src/Component/Footer.js, frontend/src/style/Footer.css
modify footer page 
some issues in alignment
now issue is solved
I'm a GSSOC Contributor.
=> Modify Footer page

README.md
#1511 
I have added all the .md files to main readme files creating separate sections
- [ yes] Documentation update
https://github.com/user-attachments/assets/9b397eb6-f02d-447d-9a4b-744d504e496d
=> added .md files to main readme

frontend/src/DB/product.json
issue: #1483 
Duplicate tool card removed from the project.
https://github.com/user-attachments/assets/779bb1e9-4b90-4f33-8121-50fcf513c213
@HimanshuNarware  and @panwar8279 , please check my changes and merge the changes to  make contribution to the project.
=> Title : duplicate code pen tool card removed

frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/style/BookMark.css
Fixed issue #1602 
I have added a tag instead of the () which was there to display the count of bookmarks
https://github.com/user-attachments/assets/211efd68-9f0b-41e8-b7e6-1c99a291aa6f
=> Added the bookmark tag to display count of bookmarks

frontend/src/Component/Faq.js, frontend/src/style/faq.css
Under #1603 assigned to me I improved the border
Earlier it was a plain white border, I made it in a border with gradient also the gradient is moving which gives very subtle and beautiful effect , it looks very minial yet classy and elegant
heres a video of how borders looks and how it continously moving and glowing
https://github.com/user-attachments/assets/fa07abcf-6772-4b75-aab8-f1c09b080408
=> Border improved #1603

frontend/src/style/Home.css
Under #1601 assigned to me , i improved the hover effect
Earlier due to translate property the card skewed and didnt look very appealing alos, skewing made the content more blur which in turn made it even hard for users to see what they hovered because they were interested, i changed that and made hover effect more smoother elegant which makes it more user friendly as well as appealing and elegant
https://github.com/user-attachments/assets/2c9a340e-c04e-43a9-a78f-bc7ededb946b
=> hover effect improvised #1601

frontend/src/DB/product.json
Added Habitica
Issue #1612 
Added Habitica
NIL
NIL
=> Added Habitica

frontend/src/DB/product.json
issue  : #1636 
Power drill Ai platform is added to the project.
https://github.com/user-attachments/assets/531df76c-3eb3-4f82-aa7c-6cb07b1d6061
@HimanshuNarware and @panwar8279 , please check my changes and merge the changes to the project.
Thank you
=> Title:- Powerdrill Ai platform added to project

frontend/src/DB/product.json
Added Slite
Issue #1616 
Added Slite
NIL
NIL
=> Added Slite

frontend/src/DB/product.json
Added Raindrop
Issue #1614 
Added Raindrop
NIL
NIL
=> Added Raindrop

frontend/src/DB/product.json
Added Otter.ai
Issue #1613 
Added Otter.ai
NIL
NIL
=> Added Otter.ai

frontend/src/DB/product.json
Added Flipboard
Issue #1615
Added Flipboard
NIL
NIL
=> Added Flipboard

frontend/src/DB/product.json
Added clickup
Issue #1611
Added clickup
NIL
NIL
=> Added clickup

frontend/src/DB/product.json
=> spline added

frontend/src/DB/product.json
=> aiseo added

frontend/src/DB/product.json
=> bubble added

frontend/src/DB/product.json
=> reply io added

frontend/src/DB/product.json
=> zapier added

frontend/src/DB/product.json
=> logo ai added

frontend/src/pages/BackendTools.jsx
fixed https://github.com/HimanshuNarware/Devlabs/issues/1519
added firebase for backend tools
Firebase is a set of backend cloud computing services and application development platforms provided by Google.
=> added firebase in backend

frontend/src/DB/product.json
=> namelix added

frontend/src/App.js, frontend/src/Component/Footer.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Profile.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/style/Navbar.css, frontend/src/style/Profile.css
=> added profile page

frontend/src/Component/Home.js
#1564
the video file is not supporting so i uploaded images 
- [ x] I have performed a self-review of my code
=> modify search functionality

frontend/src/style/faq.css
#1546 
There was huge white gap on right side that has been fixed,alignment issues have been fixed,faq box outer border animation has been increased to give whirl effect.Whole container centered with proper styling
https://github.com/user-attachments/assets/4c74b2aa-86cf-4e12-9f1c-c993e0fd9450
=> FAQ modified

frontend/src/Component/Pagination.js, frontend/src/style/About.css, frontend/src/style/Home.css, frontend/src/style/Pagination.css
The profile pictures on the About Us page and the contribution section are not properly set.
The profile pictures are now set up correctly, and the pagination has been modified.
https://github.com/user-attachments/assets/0f91a4ed-82ac-4900-95a3-cf09296582c1
I'm a Gssoc Contribution.
=> modify about us page

frontend/src/DB/product.json
issue  : #1638 
It is an online movie streaming platform users can view the multiple movies and web series in the platform.
https://github.com/user-attachments/assets/59efbe0c-cd22-46c5-8da3-c10b4575b9eb
@HimanshuNarware  and @panwar8279 , please check my changes and merge the changes to  make contribution to the project.
Thank you
=> Title:- Tubi tv platform added to project

frontend/src/pages/BackendTools.jsx
fixed #1518 
Added Apache Server for backend tools
=> Added Apache Server

frontend/src/DB/product.json
Fixes #1548
Added CNCF in coding.
=> Added CNCF

README.md
#1635 
Add feature in section
- [yes ] Documentation update
=> Add feature in section

frontend/src/pages/Extension.jsx
=> added new extension Proofhub

frontend/src/DB/product.json
=> add khan academy

frontend/src/pages/Collaboration.jsx
fixes #1651 
most popular collaboration tool 
=> add google meet

frontend/src/pages/Productivity.jsx
fixes #1654 
Calendly is an online scheduling tool that simplifies the process of booking meetings by automatically coordinating availability between users.
=> add calendly

frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/ChatBot/ActionProvider.jsx, frontend/src/ChatBot/MessageParser.jsx
Fixes #578 
To solve this issue, I added an action for handling the empty message. I also made necessary code changes in the message provider.js
https://github.com/user-attachments/assets/ebc4daec-8d07-489d-907b-068eae2cc5ee
@panwar8279 I also tried to disable the button, when the message is empty. But it has not yet been supported by 'react-chatbot-kit"
=> Fix: Chatbot accepting empty messages

frontend/src/Component/Footer.js, frontend/src/style/Footer.css
@panwar8279 
[Bug]: Footer Not Responsive title goes out of body #1934
close #1934
- update footer and make it responsive
https://github.com/user-attachments/assets/a67b2b41-fa64-4518-a307-f8d949913521
=> update footer and make it responsive

frontend/src/DB/product.json
Issue : #1821 
Added the Netflix website to the project.
https://github.com/user-attachments/assets/c47d814b-d5b5-4381-a458-48e639811b8f
@HimanshuNarware and @panwar8279 , please check my changes and merge the changes to make contribution to the project.
Thank you
=> Netflix website added to the project

frontend/src/Component/BackToTopButton.js, frontend/src/style/BackToTopButton.css
fixes: #1919
Hey @HimanshuNarware ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar scroll to top button present on the website.
@panwar8279 @HimanshuNarware
=> update add progress in border circle, not in background DONE!

frontend/src/style/BookMark.css, frontend/src/style/Home.css, frontend/src/style/OpenSource.css
#1832
https://github.com/user-attachments/assets/58cde180-ae23-4102-ac35-69e06368a7bd
=> Added glowing moving borders to the cards

frontend/src/pages/RemoteJobs.jsx
fixes #1846 
Remote OK is a leading remote job board that helps job seekers find remote work opportunities across various industries, including tech, marketing, customer support, and more. The platform features job listings from companies around the world, making it easier for professionals to find jobs that allow them to work from anywhere. Remote OK also provides resources and tools to support remote work and job searching.
=> Added remote Ok in remote jobs

frontend/src/pages/RemoteJobs.jsx
fixes #1844 
"Upwork is a global freelancing platform where businesses and independent professionals connect and collaborate remotely. Upwork offers a wide range of freelance jobs across various categories including tech, design, writing, and more. The platform provides tools for hiring, managing, and paying freelancers, making it easier for businesses to find the right talent and for freelancers to find rewarding projects."
=> Added upwork in remote jobs

frontend/src/pages/FrontendTools.jsx
fixes #1847 
"Webpack is a module bundler for modern JavaScript applications. It compiles small pieces of code, known as modules, into a cohesive bundle for use in the browser. Webpack enables developers to manage dependencies, perform code splitting, and implement hot module replacement to enhance development efficiency. It works with a wide variety of file types and seamlessly integrates with popular frameworks and libraries, supporting both ES6 and CommonJS module formats."
=> added webpack in frontend tools

frontend/src/DB/product.json
=> codingTrain added

frontend/src/DB/product.json
=> Added mimo as per issue #1839

frontend/src/DB/product.json
=> added holopin as per issue #1838

frontend/src/DB/product.json
=> added digital ocean as per issue #1837

frontend/src/DB/product.json
issue #1836 
Added patreon as per issue #1836
=> Added patreon as per issue #1836

frontend/src/DB/product.json
Added Dorahacks
Issue #1835 
Added Dorahacks
NIL
NIL
=> Added Dorahacks

frontend/src/pages/Movie.jsx
Solves #1894
I have removed the incorrect contents on the Movie & Series page and added correct contents in its place .
https://github.com/user-attachments/assets/9c8a4559-776b-4b21-9c46-f07f5b4bba19
=> Corrected contents on Movie & Series page .

frontend/src/DB/product.json
=> invision added

frontend/src/DB/product.json
=> kattis added

frontend/src/DB/product.json
=> interviewcake added

frontend/src/DB/product.json
=> paiza added

frontend/src/DB/product.json
=> hackerblocks added

frontend/src/pages/Collaboration.jsx, frontend/src/pages/FrontendTools.jsx
close #1670
Documents & diagrams for engineering teams
All-in-one markdown editor, collaborative canvas, and diagram-as-code builder
=> ADD Eraser Tool 

frontend/src/pages/FrontendTools.jsx
close #1490
Mamba UI is a toolkit for developers and designers to make creating interfaces easier. We have some of the most popularly used components to help you get started. Everything is modular and customizable to fit your brand. From blogs to portfolios to online stores, you can quickly create a variety of layouts that look great on any screen.
=> ADD Mamba UI in Frontend

frontend/src/DB/product.json
=> uxpin added

frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Navbar/NavbarItem.js, frontend/src/Component/Navbar/NavbarRight.js, frontend/src/style/Footer.css, frontend/src/style/Navbar.css
I Enhanced Mobile view of Footer Links by alligning them perfectly - Solved #1901 
Kindly Please go through this PR @panwar8279
=> Enhanced Mobile view of Footer Links

frontend/src/DB/product.json
Fixes #1498 
Add Mobile Simulator - Responsive Testing Tool in extensions.
=> Added Mobile Simulator - Responsive Testing Tool

frontend/src/DB/product.json
=> Added Poshmark as per issue #1873

frontend/src/DB/product.json
=> Added Stitch fix as per issue #1872

frontend/src/DB/product.json
=> Added Cuebric as per issue #1871

frontend/src/DB/product.json
=> Added Stablediffusion as per issue #1870

frontend/src/DB/product.json
=> miro added

frontend/src/DB/product.json
=> Moqups added

frontend/src/DB/product.json
=> dora added

frontend/src/DB/product.json
=> sketch added

frontend/src/DB/product.json
Fixes #1457, #1452, #1454, #1448, #1806, #1771, #1869, #728, #1076, #1005
#1095 , #1086 , #1084, #1078 
Added almost 16 tools in database.
I have checked not to add duplicate tools in the database.If any occurred i will remove in my next PR
=> New Tools: ADDED NEW 16 TOOLS

frontend/src/DB/product.json
Fixes #1747, #1746, #1745, #1744
#1723, #1722, #1720, #1715, #1712
#1711, #1743, #1676, #1679
#1702, #1703, #1704 
16 Different Tools Added.
=> New Tools: 16 New Tools Added

frontend/src/DB/product.json
=> vidnoz added

frontend/src/DB/product.json
=> circleback added

frontend/src/DB/product.json
=> 10web added

frontend/src/DB/product.json
#2006 
Features a large library of movies available for free streaming in high quality, with a focus on providing the latest releases and classics.It features a large library of movies available for free high-quality streaming
Close #2006
=> added AZmovies

frontend/src/DB/product.json
#2008
Provides access to a broad range of movies and TV shows for free, with options to search by title, genre, and release year.It provides free access to a broad range of movies and TV shows
CLOSE #2008
=> Added watch-free

frontend/src/DB/product.json
#2009 
Features a large collection of movies and TV series available for free streaming, with options to filter by genre, release date, and popularity.
Close Issue : #2009
=> Added Fmovies

frontend/src/DB/product.json
#2010
A popular site for free movie and TV show streaming, featuring an easy-to-navigate layout and a diverse range of genres and categories.
close #2010
=> added go movies

frontend/src/DB/product.json
=> code combat added

frontend/src/DB/product.json
=> codinGame added

frontend/src/DB/product.json
=> edabit added

frontend/src/DB/product.json
=> Added Clipchamp as per issue #1874

frontend/src/DB/product.json
#2011 
Offers free streaming of a wide variety of movies and TV shows, with high-quality video and minimal ads, allowing users to filter by genre and country.
Close issue #2011
=> added solar movie

frontend/src/DB/product.json
=> Added miro

frontend/src/DB/product.json
=> Added yahoo 

frontend/src/DB/product.json
=> Added hitv

frontend/src/DB/product.json
=> Added goodbudget

frontend/src/DB/product.json
=> Added honey due

frontend/src/DB/product.json
Fixes #2143, #2142, #2140, #2141, #2137, #2129, #2117 , #2077, #2076
Added 9 tools
=> New Tools: Added 9 Tools

frontend/src/DB/product.json
=> Added simplifi

frontend/src/DB/product.json
=> Added Dropin

frontend/src/DB/product.json
=> added leetcode explained extension as per issue #2040

frontend/src/DB/product.json
=> Added pictochart

frontend/src/DB/product.json
=> Added visme as per issue #1702

frontend/src/DB/product.json
=> Added venngage

frontend/src/DB/product.json
=> Added Appypie as per issue #1704

frontend/src/DB/product.json
=> Added freshbooks as per issue #1889

frontend/src/DB/product.json
=> Added square as per issue #1887

frontend/src/DB/product.json
=> Added Asana as per issue #1888

frontend/src/DB/product.json
=> Added Trello as per issue #1886

frontend/src/DB/product.json
=> Added Mailchimp

frontend/src/DB/product.json
=> Added evernote as per issue #1884

frontend/src/DB/product.json
=> Added Autodesk as per issue #1869

.github/workflows/check_duplicate_tools.yml
Fixes #1416 
I have added GitHub Workflows for checking duplicate tools pushing into the codebase.
=> Fix: Adding workflows for checking duplicate tools

frontend/src/DB/product.json
#1816 
added text2sql ai
- [ y ] Documentation update
=> Updated text2sql ai

frontend/src/DB/product.json
=> Added starknet iin the tools section

frontend/src/DB/product.json
issue : #1822 
Disney plus movies streaming platform added to the project.
https://github.com/user-attachments/assets/14b52497-dd7a-4262-9e71-700ac589253c
@HimanshuNarware and @panwar8279 , please check the changes and merge the changes to make contribution to the project.
Thank you
=> Title:- Disney plus movies streaming platform added to the website

frontend/src/DB/product.json
#2044
https://1drv.ms/v/c/c18cc0ab65fe88c5/ERJNATrlDX9Jm8S7Hnki-ykBcivlBtEYQoeM7jVd1PF6Rw?e=6LBMbB
=> added FutureLearn

frontend/src/DB/product.json
=> Added Savee

frontend/src/DB/product.json
Issue: #1769 
Tree house coding platform added to the project.
https://github.com/user-attachments/assets/98693c4d-054d-49de-ab62-b6b9e50113ed
@HimanshuNarware and @panwar8279 , please check my changes and merge the changes to the project to make contribution to the project.
Thank you
=> Title:- tree house coding platform added

frontend/src/DB/product.json
=> Added room sketcher

frontend/src/DB/product.json
Fixes #2161 
A site that helps you find open-source projects to contribute to by delivering issues directly to your inbox.
=> Fixes issue #2161

frontend/src/DB/product.json
#2167 
CodePen is an ideal environment for web developers and designers to prototype their ideas quickly. Whether sketching out a new design concept, testing a unique user interface, or experimenting with code, CodePen's live preview feature lets you see the results in real time.
https://github.com/user-attachments/assets/4b19c946-8d74-4143-9b8d-9dc3e3ad58b1
=> added codepen

frontend/src/DB/product.json
issue
closes #2061 
This web application is designed to significantly enhance your security by detecting unauthorized access in real-time. Whether it’s safeguarding your home or office, this web app ensures that you are promptly alerted to any potential intruders, providing you with the peace of mind that your property is protected around the clock.
[Security-Camer-AI.webm](https://github.com/Vaibhav-kesarwani/Security-Camera-AI/assets/116189379/45231ad5-9779-4fae-ad95-824afcbfccad)
=> Added Security Camera AI

frontend/src/DB/product.json
Fixes #2070 issue
I added glassdoor to remote section
@panwar8279, view this PR
=> Added Glassdoor 

frontend/src/DB/product.json
=> added python tutor tool  as per issue #2041

frontend/src/DB/product.json
=> added resumenerd as per issue #2104

frontend/src/DB/product.json
#2153 
Provides free resume templates in various styles and formats.
https://github.com/user-attachments/assets/b2c0e82c-40c5-4373-a25d-963ce8f7a546
=> Added Hloom

frontend/src/DB/product.json
Fixes #2293 , #2291 #2290 , #2286 , #2283 , #2282 #2281, #2280,
#2279, #2278, #2276, #2274 , #2271, #2261, #2257, #2236, #2232, #2231 , #2230 , #2219 , #2217 #2216 , #2211
#2210, #2206 , #2205 , #2180 
28 Tools Added.
=> New Tools: 28 Tools added

frontend/src/DB/product.json
Fixes #1552
Added KodeKloud Platform.
=> Added KodeKloud Platform 

frontend/src/DB/product.json
Fixes #2097 
removed duplicate tools in our product.json
<!- [X] - put a cross/X inside [] to check the box -->
@panwar8279, I have not deleted any extra tool in removing duplicate tools.
=> Fix: Duplicate Tools Removed. 

frontend/src/DB/product.json
Issue #2359 
Added Katalon
NIL
NIL
=> Update product.json as per issue #2359

frontend/src/DB/product.json
Fixes #2053
Added Site Palette.
=> Added Site Palette

frontend/src/DB/product.json
#2258 #2257 #2256 
Three useful tools are added.
=> new tools are added

frontend/src/DB/product.json
=> Added Muzli

frontend/src/pages/Collaboration.jsx
fixes #1942
Ryver: A collaboration platform that integrates team communication with task management and workflow automation.
=> feat: add ryver collaborating platform

frontend/src/pages/Collaboration.jsx
fixes #1946
Glip: A messaging and collaboration tool by RingCentral that offers team messaging, task management, file sharing, and video conferencing in one place.
=> feat: add glip new collaboration platform

frontend/src/pages/Collaboration.jsx
fixes #1944
Bitrix24: A complete suite of social collaboration, communication, and management tools for organizations, including project management, document sharing, and CRM.
=> feat: add bitrix new collaboration tool

frontend/src/pages/Collaboration.jsx
fixes #1945
Zoho Connect: A team collaboration software that brings people, resources, and apps together on a single platform to create a connected workplace.
=> feat: add zoho connect

frontend/src/DB/product.json
=> Update product.json as per issue#2359

frontend/src/DB/product.json
#2060 
a search engine that emphasizes protecting user privacy and does not track users' searches
=> duckduckgo

frontend/src/DB/product.json
#2059 
FTTT (If This Then That) is a popular integration tool that enables users to connect various web services and devices to automate tasks.
=> added ifttt

frontend/src/style/About.css
@panwar8279 
[Bug]: Make About us responsive #1985
close #1985
- created about us section responsive so it  open perfectly in responsive devices
https://github.com/user-attachments/assets/b1415bc6-ea92-4c3b-b2f5-f7b03e1f3ef8
=> responsive about us section

frontend/src/DB/product.json
Issue #2235 
added celestial
NIL
NIL
=> Update product.json as per issue #2235

frontend/src/DB/product.json
Issue #2236 
added lgtravels
NIL
NIL
=> Update product.json as per issue #2236

frontend/src/style/OpenSource.css
#1813 
I improved hover effect , earlier , the hover effect in open source component looks very odd , when one hover over something it means he/she is interested so that component should be more enhanced for him/her, here instead the hover effect scales down that card which is undesirable. 
What i did was:
i  scale up component on hover make it appealing and also give more shadow which will make it more beautiful and eye-catchy
You can seee improved effect here:
https://github.com/user-attachments/assets/88a4d1c9-eb6d-4f21-a949-12da5da6ffd4
=> Improve hover effect in open source

frontend/src/DB/product.json
#2154 
CakeResume provides a drag-and-drop interface and extensive customization options, enabling users to easily add, rearrange, and format sections. This makes it ideal for creating unique and visually appealing resumes tailored to specific job applications or personal branding.
https://github.com/user-attachments/assets/827ac1d9-f66e-4175-b0ba-4a31b0d123e6
=> Added CakeResume

frontend/src/DB/product.json
=> Add phpstorm

frontend/src/DB/product.json
Issue #2353 
added web catalog
NIL
NIL
=> Added web catalog as per issue #2353

frontend/src/DB/product.json
Issue #2353 
Added oyster card
NIL
NIL
=> Update product.json as per issue #2353

frontend/src/DB/product.json
Issue #2353 
added softonic
NIL
NIL
=> Added softonic as per issue #2353

frontend/src/DB/product.json
Issue #2353 
added sap
NIL
NIL
=> Added  SAP as per issue #2353

frontend/src/DB/product.json
Issue #2353
added share zone
NIL
NIL
=> Added share zone as per issue #2353

frontend/src/DB/product.json
Issue #2353 
added uni app
NIL
NIL
=> Added Uni app as per issue #2353

frontend/src/DB/product.json
=> BigThink added

frontend/src/DB/product.json
=> OpenCulture added

frontend/src/DB/product.json
=> HarvardOnline added

frontend/src/DB/product.json
=> StanfordOnline added

frontend/src/DB/product.json
=> CVMaker added

frontend/src/DB/product.json
=> FutureLearn added

frontend/src/DB/product.json
=> Pluralsight added

frontend/src/DB/product.json
=> ADDED  CHOOSINGTHERAPY

frontend/src/DB/product.json
Issue #2420 
added deliveroo
nil
=> Update product.json as per issue #2420

frontend/src/DB/product.json
=> Update product.json as per issue #2473

frontend/src/DB/product.json
=> ADDED  KROHNE

frontend/src/DB/product.json
=> ADDED KROHNE

frontend/src/DB/product.json
=> ADDED  ECOMATE

frontend/src/DB/product.json
=> ADDED WELL MIND

frontend/src/DB/product.json
=> ADDED REFLECTLY

frontend/src/DB/product.json
=> ADDED CROMA

frontend/src/DB/product.json
Fixes #2165 
1. newsletter categories to news
=> Fix: Cleaning product.json

frontend/src/DB/product.json
=> ADDED INDIAMART

frontend/src/DB/product.json
=> ADDED  JUSTDIAL

frontend/src/DB/product.json
=> ADDED SAFEWISE

frontend/src/DB/product.json
=> ADDED CIS SECURITY 

frontend/src/DB/product.json
=> ADDED DELINA

frontend/src/DB/product.json
=> ADDED APPTEKA

frontend/src/DB/product.json
=> Added flatpak

frontend/src/DB/product.json
=> Added flathub as per issue #2473

frontend/src/DB/product.json
=> Added ente app

frontend/src/DB/product.json
Fixes #1314 
- Removed 31 Duplicate Tools
1. Circleback
2. Fake Name Generator
3. Dora
4. Vinage
5. MuLearn
6. HoneyDue
7. Webcatalog
8. PluraSight
9. Softonic
10. Invideo
11. Katalon
12. GoodBudget
13. Trello
14. Stability Ai
15. Khan Academy
16. Free Code Camp
17. Frontend Mentor
18. OBS Studio
19. Codeacademy
20. Coding Ninjas 
21. Take U Forward
22. Canva
23. Fkexbox Froggy
24. Magic UI
25. Edabit
26. Forage
27. 10Web
28. Moqups
29. Simplilearn
30. Sketch 
31. Student AI
32. MIT OpenSource
I have checked twice, but no unique tools were deleted.
=> Fix: Removied 31 Duplicate Tools in Product.json.

frontend/src/pages/CoursesPlatform.jsx
fixes #1947 
LearnWorlds: A platform for creating, selling, and marketing online courses with interactive features.
=> feat: add learnworld course platform

frontend/src/DB/product.json
=> Update product.json AS PER ISSUE #2525

frontend/src/pages/Collaboration.jsx
fixes #1940
Flock: A messaging and collaboration tool that includes team messaging, video conferencing, and productivity tools.
=> feat: add Flock collaboration tool

frontend/src/DB/product.json
=> Added Auglio

frontend/src/DB/product.json
=> Added Banuba

frontend/src/DB/product.json
#2251 #2252 #2250 #2249 
four new tools are added
=> new tools added

frontend/src/DB/product.json
fixes #2294
Added spring initializr.
- [] I have commented my code, particularly in hard-to-understand areas.
=> Added spring initializr

frontend/src/DB/product.json
=> ADDED ROBLOX

frontend/src/DB/product.json
=> ADDED OXFAM

frontend/src/DB/product.json
=> ADDED THE GUARDIAN

frontend/src/DB/product.json
=> Added Intellij-idea

frontend/src/DB/product.json
=> added Ubuy india

frontend/src/DB/product.json
Fixes #1549 
Added MLH Fellowship.
=> Added MLH Fellowship

frontend/src/DB/product.json
issue : #1770 
JS Bin frontend development tool added to the project.
https://github.com/user-attachments/assets/4b421e5e-e9b0-4de9-92e1-a09764b52e61
@HimanshuNarware and @panwar8279 , please check the changes and merge the changes to make contribution to the project.
Thank you
=> Title:- Js Bin added to project

frontend/src/DB/product.json
closes #2321 
A variety of AI APIs, including those for text-to-speech, language detection, sentiment analysis, face recognition, question answering, data anonymization, and other technologies, are available on Eden AI's platform.
The Eden AI platform offers a variety of technologies, including text-to-speech, language detection, sentiment analysis, face recognition, question answering, and data anonymization.
[Screencast from 27-07-24 07:53:15 PM IST.webm](https://github.com/user-attachments/assets/ba044f29-5d79-4be1-a010-62279ef25195)
[Include any additional …
=> Added Eden AI

frontend/src/DB/product.json
=> added Price History Extension

frontend/src/DB/product.json
=> banuba tool added

frontend/src/DB/product.json
=> pixcet tool added

frontend/src/DB/product.json
=> pypl added

frontend/src/DB/product.json
=> framer tool added

frontend/src/DB/product.json
Fixes #2069 issue
I added HBO Max to movies
=> Add HBO Max

frontend/src/DB/product.json
Fixes #2159 issue
Added VS Studio Code
=> Add Visual Studio Code

frontend/src/DB/product.json
#2653 
Added new tool DevZero that provides developers customised software solutions for production, Editor and create a workspace environment.
=> Added DevZero

frontend/src/DB/product.json
#2651 
Added new tool - edclub
It is an e-learning platform.
=> Added edclub

frontend/src/DB/product.json
=> Added webstorm

frontend/src/DB/product.json
=> FutureMe tool added

frontend/src/DB/product.json
=> Libro added

frontend/src/DB/product.json
Fixes #2068 issue
Added StayFocused Extension 
=> StayFocused Extension

frontend/src/DB/product.json
Fixes #2067 issue
I added ghostery extension to extensions category
=> Add Ghostery Extension

frontend/src/DB/product.json
=> Added wamp server

frontend/src/DB/product.json
=> Added xampp server

frontend/src/DB/product.json
=> MeisheSDK tool added

frontend/src/DB/product.json
=> Added "Call Of Duty"

frontend/src/DB/product.json
=> Added Project "Gutenberg"

frontend/src/DB/product.json
Fixes #2341 issue
I added GitLab tool
=> Add GitLab

frontend/src/DB/product.json
=> Added "INVISION"

frontend/src/pages/FrontendTools.jsx
Added Three.js
- [X ] Documentation update
(https://miro.medium.com/v2/resize:fit:724/1*6s_Dkfeldg35ySmAp0tPkQ.png)
- [ X] I have performed a self-review of my code
=> [Feature Request]: Want To Add New Frontend Tool Three.js #2385

frontend/src/Component/Home.js
@panwar8279 
[Bug]: Item not found still pagination displayed #2450
close #2450
https://github.com/user-attachments/assets/04ef0efe-2ffa-4227-b36a-3ac099a8f2b3
=> removed pagination if searched product not found

frontend/src/DB/product.json
#2298 
An open-source tool for creating wireframes and prototypes.
=> Added Pencil-Project

frontend/src/DB/product.json
#2300 
A free design software with built-in assets and features, similar to Sketch but available for Windows.
=> Added Lunacy

frontend/src/DB/product.json
#2301 
An open-source design and prototyping platform for cross-functional teams.
=> Added Penpot

frontend/src/DB/product.json
#2302 
Design interactive interfaces and prototypes with complex animations; ideal for high-fidelity prototypes.
=> Added Origami studio

frontend/src/DB/product.json
#2303 
Rapidly design and prototype UI/UX interfaces; offers a wide range of pre-designed components.
=> Added Mockplus

frontend/src/DB/product.json
#2305 
A design, prototyping, and collaboration tool with a free plan.
=> added marvel

frontend/src/Component/Profile.js, frontend/src/style/Profile.css
closes #2472 
- I have Improved the UI of login and sign up forms with new shadow effects and color combinations
- In the sign up form, I have added a checkbox for newsletter subscription
- I have also added a terms and condition clause in the sign up form
- In the Profile section, I have added option to add image. 
- The added image is displayed in a completely new UI in the profile page
- New icons are also added in the profile page for display
- Overall improvement is done
##before
=> feat: Profile Page updated

frontend/src/style/Home.css
Their was flickering issue when we hovered over the categories sections in the main div in home.js
fixes #2534 
- [x ] Bug fix
- x[ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
=> Fixes the flickering on the categories section

frontend/src/DB/product.json
Fixes #2344 issue
Added Eclipse to Coding section
@panwar8279 view this PR
=> Added Eclipse

frontend/src/DB/product.json
Fixes #2342 issue
A Git repository management solution designed for professional teams. It integrates with Jira, a popular issue and project tracking tool.
I added BitBucket to the tools section 
=> Added BitBucket

frontend/src/DB/product.json
=> thisissand added

frontend/src/DB/product.json
fixes #2697 
Add new ui design tool
=> Added dribble

frontend/src/DB/product.json
=> Howstuffworks added

frontend/src/App.js, frontend/src/Component/Faq.js, frontend/src/style/Profile.css, frontend/src/style/Signup.css
=> fixed signup page css

frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/style/Navbar.css
I Alligned Navbar - Solved #2295 
Kindly go through this PR @panwar8279
=> Alligned Navbar

frontend/src/Component/Home.js, frontend/src/Component/Profile.js, frontend/src/Component/Signup.js
#2565
https://drive.google.com/file/d/1HRLEGG4fJGtv-8sWJHc2zsaihLFWtzJw/view?usp=sharing
=> validation added

frontend/src/DB/product.json
=> ADDED SCREENER,INDIAAI,OWLER,PRIVCO

frontend/src/DB/product.json
=> ADDED INSTAHYRE,TRACKXN,CRUNCHBASE

frontend/src/DB/product.json
=> ADDED UNIMONT,ZAUBA,AMBITIONBOX

frontend/src/DB/product.json
=> ADDED VOICELINER,SOUNDCLOUD,FSI

frontend/src/DB/product.json
=> ADDED METROMEDI,PHARMEASY,PRACTO

frontend/src/DB/product.json
=> ADDED MAPPLS,WAZE,MEDI BUDDY

frontend/src/DB/product.json
=> ADDED PLAYSTATION,ADDITUDE,GAMESRADAR

frontend/src/DB/product.json
=> Added SciSpace

frontend/src/DB/product.json
=> Added Wiseone

frontend/src/Component/Home.js, frontend/src/style/Footer.css, frontend/src/style/Home.css, frontend/src/style/Testimonials.module.css
#2870 
Changes Made: 
1. The hero section is properly aligned
2. The margin above the footer was removed. 
3. Center the search field and category section
https://github.com/user-attachments/assets/8475d94f-2752-4db6-94e9-a4ca4c7e45fd
=> Fix:  HomePage Alignment

frontend/src/DB/product.json
Fixes #2868 
Rive allows you to design and ship interactive animations for apps, games, and websites. It’s a powerful tool for adding high-quality animations that respond to user interactions.
Cacher is a tool for storing and organizing code snippets, making it easier to reuse and share code across projects, particularly in team environments.
=> ADDED RIVE, CACHER , AND RESTYA BOARD

frontend/src/DB/product.json
Fixes:  #2545 
- Created a new pr since the old one ( #2714 ) was causing some deployment issue.
- Added courses tool (Great Learning).
@panwar8279 Please review this pr and let me know if everything is fine or not.
=> Added courses tool (Great Learning).

frontend/src/DB/product.json
closes #2658 
Tap Away is a life-saving mobile application designed to prioritize your safety during emergencies and natural calamities. By registering on the app, users gain immediate access to crucial services that can make a difference in critical situations.
<p>
</p>
=> Added TapAway

frontend/src/DB/product.json
=> Spoonflower added

frontend/src/DB/product.json
=> artbreeder added

frontend/src/DB/product.json
=> Shapeways tool added

frontend/src/DB/product.json
#2606
Shapeways tool added.
<!- [X] - put a cross/X inside [] to check the box -->
Kindly review and merge this PR.
=> shapeways added

frontend/src/DB/product.json
=> Hemingway added

frontend/src/DB/product.json
Added #809 
Added new tool github 
=> Added github

frontend/src/DB/product.json
=> Added Traqq

frontend/src/DB/product.json
=> Addded xbox,games rant,pcgames

frontend/src/DB/product.json
=> Added capterra,sourceforge,webtrit

frontend/src/App.js, frontend/src/Component/BookMark.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Slice/DataSlice.js, frontend/src/style/BookMark.css, frontend/src/style/Home.css
@panwar8279 
close #2556
- aling pagination buttons center
=> Pagination buttons center

frontend/src/App.js, frontend/src/Component/BookMark.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Slice/DataSlice.js, frontend/src/style/BookMark.css
=> Remove bookmark

frontend/src/App.js, frontend/src/Component/BookMark.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Slice/DataSlice.js, frontend/src/style/BookMark.css
@panwar8279 
close #2257
**Before**
**After**
=> Navigation aling

frontend/src/App.js, frontend/src/Component/BookMark.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/Navbar.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Slice/DataSlice.js, frontend/src/style/BookMark.css
@panwar8279 
close #2451 
- Rate us now open in model not in any route
https://github.com/user-attachments/assets/5553f914-6ea4-427b-a8ea-7656609fdbd7
=> Rate us open in model not in route

frontend/src/DB/product.json, frontend/src/pages/Extension.jsx
Closed #2588 
These issues were opened by @Kiran-pande-30 and he assigned me to work on these as he has worked on my issues reference #2591
=> Added pitnerest tools

frontend/src/DB/product.json
=> ADDED NOCODB

frontend/src/DB/product.json
Fixes #2877 
Many unnecessary extra category ranges in the product.json file.
=> Fix: Filter product.js

frontend/src/DB/product.json
Fixes #2498
Added Talend API Tester.
=> Added Talend API Tester

frontend/src/DB/product.json
=> Added Kaggle

frontend/src/DB/product.json
Fixes #2497
Added Postman Interceptor.
=> Added Postman Interceptor

frontend/src/DB/product.json
=> Added Smart TOC

frontend/src/DB/product.json
#2960
Added SPOJ (Sphere Online Judge)
=> Added SPOJ (Sphere Online Judge)

frontend/src/DB/product.json
=> Added AlgoExpert

frontend/src/DB/product.json
Fixes #2877
Removed duplicates of following tools
Eclipse
Sublime Text
Invision App
Krohne
Gitlab
FileHippo
Banuba
Instahyre
moneycontrol
roblox
developer
inasp
the guardian
oxfmaindia
Student AI
Epic Games
Framer
Api Dog
Bit Bucket
Coding Ninjas
takeUForward
Canva
MagicUI
Edabit
Appy Pie
Vennage
Mulearn
Simplilearn
Sketch
IPlogger
algoprep
OCW MIT edu
Plural Sight
Acerternity
Skill Share
TeamTreeHouse
Alison
=> Fix: Duplicate: 40 duplicate removed

frontend/src/DB/product.json
=> added a tool

frontend/src/DB/product.json
Fixes https://github.com/HimanshuNarware/Devlabs/issues/2416
Added new tool devhints .
=> Added devhints

frontend/src/DB/product.json
=> Added capterra,webtrit,sourceforge

frontend/src/DB/product.json
Fixes: #2867 
Teleport offers a unified access plane for managing secure access to critical infrastructure, simplifying complex security operations for developers.
Raycast is a powerful launcher that allows developers to quickly access files, run scripts, and manage tasks with keyboard shortcuts, enhancing workflow efficiency.
=> Added teleport, Raycast

frontend/src/DB/product.json
=> ADDED SMASHING MAGAZINE DEVELOPER TOOL

frontend/src/DB/product.json
=> Added opencollective,bandcamp,games8

frontend/src/DB/product.json
=> Addded tura,turi,superdash

frontend/src/DB/product.json
=> Added XBOX,PCGAMES,GAMES RANT

frontend/src/DB/product.json
Closes #2713 
Blooket: An educational platform where teachers can create games and quizzes that students can play to learn in a fun and interactive way.
=> Add Blooket

frontend/src/DB/product.json
Closes #2712
Fathom: A podcast player that allows users to discover, save, and share highlights from podcasts.
=> Add Fathom

frontend/src/DB/product.json
Closes #2711
Tabby: An open-source terminal emulator for a variety of platforms. It aims to provide a customizable and extensible terminal experience.
=> Added "Tabby"

frontend/src/App.css, frontend/src/App.js, frontend/src/Component/Footer.js, frontend/src/Component/Home.js, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/Rate.css, frontend/src/Component/Rateus.js, frontend/src/Component/Sidebar/Sidebar.js, frontend/src/style/Footer.css, frontend/src/style/Home.css, frontend/src/style/Modal.css, frontend/src/style/Navbar.css, frontend/src/style/Rateus.css, frontend/src/style/Sidebar.css
I Added  Emojis  instead of Stars  and Toastify Message too - Solved #2602 
Kindly go through this PR @panwar8279 
https://github.com/user-attachments/assets/07d99566-3843-43da-b0ad-851d2de6ef5b
=> Addition of Emojis

frontend/src/App.js
I Fixed Footer by alligning it perfectly - Solved #2455
Kindly go through this PR @panwar8279 
https://github.com/user-attachments/assets/2ef365bd-c361-4c30-8e17-70e2baa43a8e
=> Fixed Footer

frontend/src/DB/product.json
=> ADDED PINE GROW

frontend/src/App.js
I Enhanced RateUs Option - Solved #2468
Kindly go through this PR @panwar8279
https://github.com/user-attachments/assets/9a4ff117-0323-4475-91e8-8a7d1a16d9b5
=> Enhanced RateUs

frontend/src/App.css, frontend/src/App.js
I Added BoxShadow Effect - Solved #2643
Kindly go through this PR @panwar8279 
https://github.com/user-attachments/assets/7a800568-33e3-4cb7-9e60-a7d68f2c8198
=> Added BoxShadow Effect

frontend/src/Component/Home.js, frontend/src/DB/product.json
=> Pdf tool edit pdfs online 

frontend/src/DB/product.json
=> Website speed insights analysing onlie tool

frontend/src/DB/product.json
=> Added plagrism checker by grammerly

frontend/src/DB/product.json
=> creddle added

frontend/src/DB/product.json
=> Added "Pencil-Projects"

frontend/src/DB/product.json
=> Added "Dillinger"

frontend/src/DB/product.json
=> Added "Obsidian"

frontend/src/DB/product.json
=> Added "Figma Jam"

frontend/src/DB/product.json
=> Added "Tiddlywiki"

frontend/src/DB/product.json
#2725 
With the easy-to-use HubSpot CRM, you’ll never manually update reports or wonder how your team is tracking toward quotas
=> Added hubspot

frontend/src/DB/product.json
closes #2690 
Spline is a free 3D design software with real-time collaboration to create web interactive experiences in the browser. Easy 3d modeling, animation
[Screencast from 06-08-24 03:27:27 PM IST.webm](https://github.com/user-attachments/assets/6f303951-f45f-4c4c-9bfd-36f024cc8b10)
=> Add Spline

frontend/src/DB/product.json
Closes #2708
Streamlit: An open-source app framework for Machine Learning and Data Science teams to create and share data applications quickly.
=> Added 'Streamlit'

frontend/src/DB/product.json
=> added asciinema

frontend/src/DB/product.json
Closes #2715
Linear: A project management tool focused on creating, tracking, and managing tasks efficiently, particularly for software development teams.
=> Added Linear

frontend/src/DB/product.json
#2724 
New tool: Digital samaritan added
=> Added Digital Samaritan
