src/style/Home.css
**What does this pr do ?**
This pull request aims to resolve the "Link and Bookmark Button Overlap Issue (#64)" by making changes to the CSS code in the "Home.css" file. Specifically, it adjusts the styling of the main container to prevent the overlap issue between the link and bookmark buttons on the webpage. The changes ensure that the buttons are properly spaced and do not overlap, thus improving the visual display and user interface.
Fixes : #64 
**Expected behavior**
The link and bookmark buttons should be properly spaced and not overlap, ensuring a clean and user-friendly interface.
**Screenshots**
- Before
- After
=>  Resolving Link and Bookmark Button Overlap Issue (#64)

src/DB/product.json
Fixes incorrect link in Devlabs one-vercel-app:  https://devlabs-one.vercel.app/
- This PR is the submission to the issue #135
=>  bug: fixes incorrect link for big-omega

src/DB/product.json
This PR fixes a bug issue due to an incorrect link.
- This is the submission to issue #134
=> bug: Saop2Day page is not loading on the devlabs one -vercel -app

frontend/src/Component/Navbar/NavbarRight.js
Added a bootstrap class invisible so hide the cross icon.
Could have made button element appear on searchQuery but Navbar layout then gets changed everytime searchQuery is empty.
=> fix: Issue/291- Search Bar

frontend/src/style/About.css, frontend/src/style/Pagination.css
Issue Number #374 
In the about us section there are buttons like star the repo and learn more in which there should be more padding to look good. I fixed that problem. Also, I sorted the pagination bug in which active page goes above the nav bar.
Before
After
=> Proper Padding to buttons

frontend/src/Component/Footer.js
fixes #373 
This PR fixes the footer social icons not visible issue. Now they are visible for the social icons
- [ x] Bug fix
- [ x] I have performed a self-review of my code
=> fix issue :Footer social icons not visible

.github/workflows/close-old-pr-woc.yml
Fixes #410 
Implemented a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.
=> added workflow for closing old PRs

frontend/public/index.html, frontend/src/Component/Footer.js, frontend/src/style/Footer.css
[The Twitter logo used in this project is outdated. It will be changed to the updated version. #436]
To resolve the bug with the Twitter icon, I implemented changes across three sections:
1. Added Font Awesome JavaScript link to index.html in the public folder within the frontend directory.
2. Inserted FontAwesome Twitter icon code into Footer.js located in the Src folder within the frontend directory.
3. Wrote CSS code in Footer.css within the style folder inside the Src directory.
These adjustments successfully fixed the bug.
https://github.com/HimanshuNarware/Devlabs/assets/106450463/1ec237a1-30ea-4b76-b9c0-a07482a4ad3d
[Include any additional …
=> Changed outdated Twitter icon to updated version X. 

frontend/src/style/NotFound.css
Closes #546 By improving the contrast ratio of text in the Error 404 page
The fixed contrast ratio works in both the themes.
=> Improved contrast of text in both themes

frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/style/Home.css
I have added the close button and fixed some errors which causes trouble when i open the website
- [ x] Bug fix
Please close this under GSSOC'24
=> Closing button was not there in chatbot

frontend/src/DB/product.json
Fixed #569 
I have fixed the logos of tools that were not loading in some browsers. The tools images fixed include:
1. w3schools
2. Javatpoint
3. ChatGPT Writer
4. Himalayas
5. KhanAcademy : The given logo was the wrong khan academy so I changed that too
6. Figma.com
7. flaticon
8. Fontshare
9. PDF24
10. Designs.ai
11. Walkccc
12. DEVPOST
13. Gitter
14. PortSwigger
15. CyberChef
16. PentesterLab
The reason why it did not work in some browser might be because all the above tools links are a link of the format "th.bing.com/" and it fails to get called on page load because that type of link is blocked by some browsers and extension. So this issue is fixed by changing it with different links.
=> Fixed images not visible in some browsers

frontend/src/pages/CodingPlateform.jsx, frontend/src/style/CodingPlateform.css
@panwar8279 
[Feature Request]: Create Coding Plateform Page #624
close #624
- `coding-plateform` page
- make it reponsive
- added hover effect
- support dark and light mode
please add level 3
=> added coding plateform page

frontend/src/App.js, frontend/src/ChatAssistant/ChatAssistant.jsx, frontend/src/index.css, frontend/src/pages/CoursesPlatform.jsx, frontend/src/style/Courses.css
@panwar8279 
[Feature Request]: Create Cource Plateform Page #625
close #625
responsive
=> [Feature Request]: Create Cource Plateform Page

frontend/src/DB/product.json
Closes #1116 
I have added a Chrome Extension which is an AI Career Copilot for 
- Automated Job Tracking 
- Optimizing your LinkedIn Profile 
- AI Resume Builder
- To keep track of all your jobs opportunities, applications, notes, contacts, in one single dashboard.
=> Added CareerFlow Extension

frontend/src/style/Navbar.css
I have fixed Devlabs heading is overlapping with sidebar
Now it is not overlapping with the sidebar 
I changes the animation applied to the heading due to which it is moving down now i fixed that 
https://github.com/HimanshuNarware/Devlabs/assets/118350936/e7f38dd7-6527-4db6-a52e-db0a7ab8def5
=> Fixed Devlabs heading is overlapping with sidebar

.github/workflows/restrict_pr.yml, frontend/src/DB/product.json
Closes #1170 
I have added the github workflow to Restrict a contributor's PR after crossing 200+ points
`ADMIN LEVEL WORK REQUIRED`
`ADMIN LEVEL WORK REQUIRED`
Steps required from your side - 
1. Create a GitHub Personal Access Token
- Go to your GitHub [Developer settings](https://github.com/settings/tokens)
- Click on Generate new token
- Select the scopes that include `repo`, `workflow`, and `admin:repo_hook`
- Generate the token and copy it. You will need it in step 2
2. Add the Personal Access Token to GitHub Secrets
- Go to your repository on GitHub
- Click on Settings
- In the left sidebar, click on Secrets and variables > Actions
- Click on New repository secret
- Name the secret `PERSONAL_ACCESS_TOKEN` and paste the token you generated in step 1
- Click Add secret
=> Restrict Contributor's PR after crossing 200+ points

frontend/src/Component/BackToTopButton.js, frontend/src/style/BackToTopButton.css
Fixes #1876 
I have a hiding property for the scroll to the top button. There is no sense in displaying a button for the upper half of the page.
https://github.com/user-attachments/assets/dd5eba9a-aed4-4cdb-bd3c-81ce8a65a608
=> Fix: scroll To Bottom Disapper for the upper half of the window

frontend/src/Component/Footer.js, frontend/src/Component/Navbar/Navbar.js
Fixes: #1850 
- Removed the blank space of right side of the home page in mobile view.
- Now the home page is looking responsive on mobile view.
https://github.com/user-attachments/assets/1befa8b8-6ddc-4db2-a6ac-b2d2d08cecc2
_Please review and merge my pull-request under GSSoC'24_
=> Removed the blank space of right side of the home page in mobile-view.

frontend/package-lock.json, frontend/src/App.css, frontend/src/Component/Contact.jsx
#2028 
completed notification pop up at contact page as mentioned in the feature.
https://drive.google.com/file/d/1fMJEacsL-eoqMSmvMoODSJafuOu7z27j/view?usp=sharing
=> contact page notification 

frontend/src/App.js, frontend/src/pages/BackendTools.jsx
Solves #2073
Now the contents on the Backend tools page is loading properly on click of the link from sidebar . Before this only footer was visible .
https://github.com/user-attachments/assets/209a5fc5-08ea-4474-9711-c6ca694302cb
I have also made the the heading Backend tools to be visible which was earlier wasn't visible .
=> Backend tools page contents are now loading properly.

frontend/src/DB/product.json
=> ADDED BALANCE APP

frontend/src/style/About.css
Solves #2415
I have fixed the overflowing of contributor section, which was flowing out of the screen .
=> Fixed overflowing of contributor section .

.github/workflows/check_duplicate_tools.yml
Fixes #2875 
The updated GitHub Actions workflow now ensures that no duplicate tools are added to the `product.json` database by checking for duplicate entries based on the `link` field instead of `productName`.
=> Fix: Fixed the duplicate tools workflows

frontend/src/DB/product.json
=> Added resumonk

frontend/src/DB/product.json
=> Added "Scrimba"

frontend/src/DB/product.json
=> Added "Carbon"

frontend/src/DB/product.json
Fixes #2718 issue
Added Pycharm 
=> Add PyCharm

frontend/src/DB/product.json
#2821 
Sourcegraph allows developers to rapidly search, write, and understand code by bringing insights from their entire codebase right into the editor.
=> Added Sourcegraph

frontend/src/DB/product.json
#2727 
Traqq is a powerful timesheet app and time-tracking software for remote and on-site teams worldwide. Track work hours, generate reports, and say goodbye to billing and payroll nightmares.
=> Added Traqq

frontend/src/DB/product.json
#2728 
iTerm2 is a replacement for Terminal and the successor to iTerm. It works on Macs with macOS 10.14 or newer. iTerm2 brings the terminal into the modern age with features you never knew you always wanted
=> Added iterm2

frontend/src/DB/product.json
Fixes #2865 
Codrops is a fantastic resource for experimental web design techniques and tutorials. It often showcases innovative UI elements and animations that can inspire unique web projects.
WebDevSimplified, along with its associated YouTube channel, provides simple explanations and tutorials on various web development topics, ideal for beginners and those looking to brush up on specific skills.
=> ADDED CODROPS AND WEBDEVSIMPLIFIED

frontend/src/DB/product.json
Closes #2716 
Retool: A platform that allows developers to build internal tools quickly using pre-built components, APIs, and databases.
=> Added Retool

frontend/src/App.css, frontend/src/ChatAssistant/ChatAssistant.css, frontend/src/Component/Navbar/NavbarCenter.js, frontend/src/Component/TrailingCursor/TrailingCursor.jsx, frontend/src/Component/TrailingCursor/TrailingCursor.module.css, frontend/src/Component/TrailingCursor/index.js, frontend/src/index.css, frontend/src/style/Home.css, frontend/src/style/Navbar.css, frontend/src/style/Profile.css
=> ui changes and bug fixing
